//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Wally.rc
//
#define ID_FILTER_PREVIEW               10
#define ID_FILTER_APPLY                 11
#define IDD_ABOUTBOX                    100
#define CG_IDR_POPUP_WALLY_VIEW         101
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    102
#define IDD_DIALOGBAR_ZOOM              103
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 104
#define IDB_SPLASH                      105
#define CG_IDR_POPUP_BROWSE_VIEW        106
#define IDS_PROPSHT_CAPTION             107
#define IDD_PROPPAGE1                   108
#define IDD_PROPPAGE2                   109
#define ID_EDIT_ZOOMIN                  110
#define ID_EDIT_ZOOMOUT                 111
#define ID_EDIT_SHIFT_LEFT              112
#define ID_EDIT_SHIFT_RIGHT             113
#define ID_EDIT_SHIFT_UP                114
#define ID_EDIT_SHIFT_DOWN              115
#define ID_STATUSBAR_PROGRESS           116
#define IDR_MAINFRAME                   117
#define IDR_WALLYTYPE                   118
#define IDR_PACKAGE_TYPE                119
#define IDR_BROWSETYPE                  120
#define IDR_BUILDTYPE                   121
#define IDR_PACKAGE_VIEW_TYPE           122
#define IDR_BROWSE2TYPE                 123
#define IDR_PAK_TYPE                    124
#define IDR_WLY_TYPE                    125
#define CG_IDR_POPUP_SHAPE              126
#define IDD_TEXTURE_INFO                127
#define CG_IDR_POPUP_DRAWING_WIDTH      128
#define CG_IDR_POPUP_AMOUNT             129
#define IDR_IMAGE_EDIT_TOOLBAR          130
#define IDR_MODES_TOOLBAR               131
#define IDD_NEW_WAL                     132
#define IDD_NEW_TEXTURE_DLG1            133
#define IDC_ZOOM_CURSOR                 134
#define IDC_PAINT_CURSOR                135
#define IDC_DROPPER_CURSOR              136
#define IDD_PALETTE_MISMATCH            137
#define IDD_WALLY_OPTIONS               138
#define IDD_REMIP_DLG                   139
#define IDD_TOOL_OPTIONS_DLG            140
#define IDB_REMIP                       141
#define IDB_OPTIONS                     142
#define IDD_PALETTE_TOOLBAR             143
#define IDD_COPYTILED                   144
#define IDB_BRUSH_SIZE                  145
#define IDB_BRUSH_SHAPE                 146
#define IDB_AMOUNT                      147
#define IDD_ROTATE                      148
#define IDD_EDGE_DETECT_DLG             149
#define IDI_ICON1                       150
#define IDI_WALLY_ICON                  151
#define IDD_BROWSE_DLG                  152
#define IDD_BATCH_DLG                   153
#define IDD_ADD_NOISE_DLG               154
#define IDD_BLEND_DLG                   155
#define IDD_BRIGHTNESS_CONTRAST_DLG     156
#define IDD_EMBOSS_DLG                  157
#define IDD_MARBLE_DLG                  158
#define IDD_UNREAL_DLG                  159
#define IDD_PALETTE_PICKER_DLG          160
#define IDD_MARBLE_TILE_DLG             161
#define IDD_FREE_UNDOS_DLG              162
#define IDD_DIFFUSE_DLG                 163
#define IDD_MIRROR_DLG                  164
#define IDD_BATCHTEMP_DLG               165
#define IDD_BC_SUMMARY_DLG              166
#define IDD_NEW_IMAGE_DLG               167
#define IDD_HALF_LIFE_PALETTE_DLG       168
#define IDD_NEW_PALETTE_DLG             169
#define IDD_PALETTE_NAME_DLG            170
#define IDD_WADPAK_VIEW_DLG             171
#define IDD_RENAME_IMAGE_DLG            172
#define IDR_PACKAGE_POPUP               173
#define IDD_ADDTO_PACKAGE_DLG           174
#define IDD_PACKAGE_CONVERT_DLG         175
#define IDD_PACKAGE_EXPORT_DLG          176
#define IDD_JUST_FOR_TESTING            177
#define IDD_SELECT_GAME_DLG             178
#define IDD_PROPPAGE3                   179
#define IDB_WALLYDOC_ICONS              180
#define IDD_DUPLICATE_NAME              181
#define IDD_OFFSET_DLG                  182
#define IDD_SHARPEN_DLG                 183
#define IDD_PALETTE_EDITOR_DLG          184
#define IDD_COLOR_TRANSLATOR_DLG        185
#define IDD_RESIZE_DLG                  186
#define IDD_REDUCE_COLORS_DLG           187
#define IDB_BITMAP1                     188
#define IDD_PROPPAGE4                   189
#define IDB_BMP_MASK                    190
#define IDD_PASTE_SPECIAL               191
#define IDB_PACKAGEDOC_ICONS            192
#define IDB_SPLASH_ON                   193
#define IDR_WAVE_FIRE                   194
#define IDR_PACKAGE_DRAG_POPUP          195
#define IDD_PROPPAGE5                   196
#define IDB_GRID                        197
#define IDB_PALETTE                     198
#define IDB_NEWTEXS                     199
#define IDR_WAVE_HUM                    200
#define IDD_DECAL_TOOLBAR               201
#define IDD_DECAL_TOOLBAR_PAGE1         202
#define IDD_BATCH_ADV_DLG               203
#define IDR_PCX_MOUSE                   204
#define IDR_PCX_MOUSE_L                 205
#define IDR_PCX_MOUSE_LRX               206
#define IDR_PCX_MOUSE_R                 207
#define IDR_PCX_MOUSE_RX                208
#define IDR_PCX_MOUSE_X                 209
#define IDR_LMP_DUKE3D                  210
#define IDR_LMP_SHADOW                  211
#define IDR_LMP_REDNECK                 212
#define IDR_BUILDVIEW_POPUP             213
#define IDD_BUILD_PROPERTIES_DLG        214
#define IDD_GAME_PALETTE_DLG            215
#define IDR_LMP_QUAKE1                  216
#define IDR_LMP_QUAKE2                  217
#define IDR_PCX_BUILDVIEW_BUTTON        218
#define IDD_NEW_PACKAGE_IMAGE           219
#define IDD_PERCENT_DLG                 220
#define IDR_PCX_WAD_THUMB               221
#define IDD_BATCH_ADV_PAGE1             222
#define IDD_BATCH_ADV_PAGE2             223
#define IDD_PROPPAGE6                   224
#define IDD_SIN_FLAGS_DLG               225
#define IDD_DIALOG2                     226
#define IDD_RULES_DLG                   227
#define IDD_DIALOG1                     228
#define IDD_NEW_RULE_DLG                229
#define IDD_SIN_RULE_FLAGS_DLG          230
#define IDR_BROWSE2_POPUP               231
#define IDR_BROWSE_POPUP                232
#define IDD_ENLARGE_CANVAS_DLG          233
#define IDD_PROPPAGE7                   234
#define IDR_PACKAGE_BROWSE_POPUP        235
#define IDB_PUSH_RANDOM                 236
#define IDB_PUSH_ANIMATE                237
#define IDB_PUSH_TILE_MODE              238
#define IDB_PUSH_BROWSE_MODE            239
#define IDR_PAK_POPUP                   240
#define IDD_PAK_IMPORT_DLG              241
#define IDD_PAK_TREE_DLG                242
#define IDD_PAK_EXPORT_DLG              243
#define IDD_DECAL_TOOLBAR_PAGE2         244
#define IDD_TOOL_SETTINGS_TOOLBAR       245
#define IDD_TOOL_SETTINGS_PAGE1         246
#define IDD_TOOL_SETTINGS_PAGE2         247
#define IDB_REMIP_HELP                  248
#define IDB_BATCH_CONVERSION            249
#define IDB_FILE_ASSOCIATIONS           250
#define IDR_LMP_BLEND                   251
#define IDD_COLOR_DECAL                 252
#define IDB_COLOR_DECAL                 253
#define IDR_WAD_PLDECAL                 254
#define IDD_WADMERGE_DLG                255
#define IDD_WADMERGE_ADD_DLG            256
#define IDD_WAD_MERGE_STATUS            257
#define IDR_TEX_TYPE                    258
#define IDD_FIX_UNEVEN_LIGHTING_DLG     259
#define IDR_PCX_WALLY_LOGO              260
#define IDC_MOVE_CURSOR                 261
#define IDC_HAND_CURSOR                 262
#define IDB_PACKAGE_TREE_IMAGE          263
#define IDR_DEFAULT_PALETTE             264
#define IDR_DEFAULT_Q2FLAGS_JSON        265
#define IDR_DEFAULT_Q2CONTENTS_JSON     266
#define IDR_NEW_MAINFRAME               269
#define IDC_TEXTURE_NAME                1000
#define IDC_WIDTH                       1001
#define IDC_HEIGHT                      1002
#define IDC_VALUE                       1003
#define IDC_ANIMNAME                    1004
#define IDC_WINDOW_CHECK                1005
#define IDC_CHECK_AUTO_REMIP            1006
#define IDC_CHECK_WINDOW                1007
#define IDC_LIGHT_CHECK                 1008
#define IDC_SLICK_CHECK                 1009
#define IDC_WARP_CHECK                  1010
#define IDC_TRANS33_CHECK               1011
#define IDC_TRANS66_CHECK               1012
#define IDC_FLOWING_CHECK               1013
#define IDC_NODRAW_CHECK                1014
#define IDC_LAVA_CHECK                  1015
#define IDC_SLIME_CHECK                 1016
#define IDC_WATER_CHECK                 1017
#define IDC_MIST_CHECK                  1018
#define IDC_EDIT_WIDTH                  1019
#define IDC_SPIN_HEIGHT                 1020
#define IDC_NEW_PALETTE                 1021
#define IDC_CONVERT_PALETTE             1022
#define IDC_NEAREST_COLOR               1023
#define IDC_INDEXED                     1024
#define IDC_PORTAL_CHECK                1025
#define IDC_EDIT_MAX_THREADS            1026
#define IDC_COMBO_TINT                  1027
#define IDC_CHECK4                      1028
#define IDC_SPIN_MAXTHREADS             1029
#define IDC_HINT_CHECK                  1030
#define IDC_PUSH_BROWSE_MODE            1031
#define IDC_TRANSLUCENT_CHECK           1032
#define IDC_EDIT_ZOOMVALUE              1033
#define IDC_SPIN_ZOOMVALUE              1034
#define IDC_CURRENTDN_CHECK             1035
#define IDC_PLAYERCLIP_CHECK            1036
#define IDC_MONSTERCLIP_CHECK           1037
#define IDC_CURRENT0_CHECK              1038
#define IDC_CURRENT90_CHECK             1039
#define IDC_CURRENT180_CHECK            1040
#define IDC_CURRENT270_CHECK            1041
#define IDC_CURRENTUP_CHECK             1042
#define IDC_SPIN_MAX_ITEMS              1043
#define IDC_ORIGIN_CHECK                1044
#define IDC_RADIO_LEFT                  1045
#define IDC_RADIO_RIGHT                 1046
#define IDC_DETAIL_CHECK                1047
#define IDC_LADDER_CHECK                1048
#define IDC_SKIP_CHECK                  1049
#define IDC_BTN_USE_RECOMMENDED         1050
#define IDC_BTN_USE_QUAKE               1051
#define IDC_RADIO_ERROR_DIFUSSION       1052
#define IDC_RADIO_WHITE_NOISE           1053
#define IDC_RADIO_NO_DITHER             1054
#define IDC_RADIO_HEAVY                 1055
#define IDC_RADIO_MEDIUM                1056
#define IDC_RADIO_LIGHT                 1057
#define IDC_RADIO_NO_SHARPENING         1058
#define IDC_RADIO_DOUBLE_WIDTH          1059
#define IDC_COMBO_RBTN_SIZE             1060
#define IDC_RADIO_HALF_WIDTH            1061
#define IDC_COMBO_LIGHTEN               1062
#define IDC_COMBO_DARKEN                1063
#define IDC_COMBO_SCRATCH               1064
#define IDC_RADIO_PALETTE_MAINTAIN      1065
#define IDC_RADIO_PALETTE_NEAREST       1066
#define IDC_STATIC_WIDTH                1067
#define IDC_STATIC_HEIGHT               1068
#define IDC_CHECK_AUTO_REMIP2           1069
#define IDC_SKY_CHECK                   1070
#define IDC_CHECK_USE_WEIGHTED          1071
#define IDC_CHECK_RETAIN_SIZE           1072
#define IDC_SOLID_CHECK                 1073
#define IDC_CHECK_REBUILD_SUBMIPS       1074
#define IDC_RADIO_WHITE                 1075
#define IDC_AUX_CHECK                   1076
#define IDC_RADIO_QUARTER_WIDTH         1077
#define IDC_EDIT_NAME                   1078
#define IDC_SPIN_WIDTH                  1079
#define IDC_COMBO1                      1080
#define IDC_TEXTUREINFO_Q2ENGINE        1081
#define IDC_COMBO_IMAGE_TYPE            1082
#define IDC_COMBO_ANIMATE_TYPE          1083
#define IDC_COMBO_GAME                  1084
#define IDC_COMBO_SURFACE_TYPE          1085
#define IDC_COMBO_GAMETYPE              1086
#define IDC_TST2_COMBO_ZOOM             1087
#define IDC_COMBO_MOD                   1088
#define IDC_COMBO_WAD_TYPE              1089
#define IDC_EDIT_HEIGHT                 1090
#define ID_COMBO_AMOUNT                 1091
#define ID_COMBO_SHAPE                  1092
#define IDC_DT_TAB                      1093
#define IDC_EDIT_WIDTH1                 1094
#define IDC_EDIT_HEIGHT1                1095
#define IDC_BTN_PALETTE                 1096
#define IDC_BTN_UI_AREA                 1097
#define IDC_CUSTOM1                     1098
#define IDC_EDIT_TILE                   1099
#define IDC_EDIT_ANIMATE_COUNT          1100
#define ID_COMBO_SIZE                   1101
#define IDC_NUMTILES_SPIN               1102
#define IDC_LEFT_RADIO                  1103
#define IDC_RIGHT_RADIO                 1104
#define IDC_90DEG_RADIO                 1105
#define IDC_180DEG_RADIO                1106
#define IDC_270DEG_RADIO                1107
#define IDC_RADIO_PRESETDIR             1108
#define IDC_RADIO_PARENTDIR             1109
#define IDC_COMBO_OUTPUT_TYPE           1110
#define IDC_EDIT_PRESETDIR              1111
#define IDC_RADIO_BLANKDIR              1112
#define IDC_EDIT_PATH                   1113
#define IDC_SELECT_BUTTON               1114
#define IDC_EDIT_MAX_ITEMS              1115
#define IDC_EDIT_BRIGHTNESS             1116
#define IDC_SPIN_BRIGHTNESS             1117
#define IDC_EDIT_CONTRAST               1118
#define IDC_EDIT_OUTPUT_FOLDER          1119
#define IDC_BUTTON_OUTPUT_FOLDER        1120
#define IDC_EDIT_FADE_IN                1121
#define IDC_RADIO_VERY_HEAVY            1122
#define IDC_SPIN_FADE_IN                1123
#define IDC_CHECK2                      1124
#define IDC_CHECK3                      1125
#define IDC_PUSH_TILE_MODE              1126
#define IDC_CHECK5                      1127
#define IDC_RADIO_VERY_LIGHT            1128
#define IDC_SPIN_CONTRAST               1129
#define IDC_CHECK_MONOCHROME            1130
#define IDC_VERY_HEAVY                  1131
#define IDC_HEAVY                       1132
#define IDC_RADIO_BLACK                 1133
#define IDC_CHECK_SEAMLESS              1134
#define IDC_BTN_JUST_DO_IT              1135
#define IDC_BTN_BACKGROUND_COLOR        1136
#define IDC_BTN_THICK_STRIPE_COLOR      1137
#define IDC_EDIT_RANDOM_SEED            1138
#define IDC_BTN_THIN_STRIPE_COLOR       1139
#define IDC_BTN_RANDOM_SEED             1140
#define IDC_EDIT_NUM_THICK_STRIPES      1141
#define IDC_SPIN_NUM_THICK_STRIPES      1142
#define IDC_CHECK_EXTRA_SMOOTH          1143
#define IDC_SPIN_AMPLITUDE              1144
#define IDC_CHECK_EXTRA_SMOOTH2         1145
#define IDC_EDIT_AMPLITUDE              1146
#define IDC_EDIT_SCALE_X                1147
#define IDC_EDIT_SCALE_Y                1148
#define IDC_EDIT_SCALE_Z                1149
#define IDC_EDIT_COLOR_VARIANCE         1150
#define IDC_EDIT_INTENSITY_VARIANCE     1151
#define IDC_EDIT_OFFSET_X               1152
#define IDC_EDIT_OFFSET_Y               1153
#define IDC_EDIT_OFFSET_Z               1154
#define IDC_EDIT_NUM_THICK_STRIPES2     1155
#define IDC_SPIN_NUM_THICK_STRIPES2     1156
#define IDC_SPIN_LEVELS                 1157
#define IDC_EDIT_LEVELS                 1158
#define IDC_EDIT_NUM_THIN_STRIPES       1159
#define IDC_SPIN_NUM_THIN_STRIPES       1160
#define IDC_SPIN_COLOR_VARIANCE         1161
#define IDC_SPIN_SCALE_X                1162
#define IDC_SPIN_SCALE_Y                1163
#define IDC_SPIN_SCALE_Z                1164
#define IDC_SPIN_OFFSET_X               1165
#define IDC_SPIN_OFFSET_Y               1166
#define IDC_SPIN_OFFSET_Z               1167
#define ID_FILTER_FAST_PREVIEW          1168
#define ID_MARBLE_PROPERTIES            1169
#define IDC_INDEX                       1170
#define IDC_RED                         1171
#define IDC_GREEN                       1172
#define IDC_BLUE                        1173
#define IDC_EDIT_INDEX                  1174
#define IDC_EDIT_RED                    1175
#define IDC_EDIT_GREEN                  1176
#define IDC_RADIO_SHAPE_RECTANGULAR     1177
#define IDC_RADIO_SHAPE_HEXAGONAL       1178
#define IDC_RADIO_SHAPE_OTHER           1179
#define IDC_BTN_GROUT_COLOR             1180
#define IDC_RADIO_STYLE_ANY             1181
#define IDC_RADIO_STYLE_PLAIN           1182
#define IDC_CHECK_GAMMA_PALETTE_TOOLBAR 1183
#define IDC_RADIO_STYLE_EXTRA_FANCY     1184
#define IDC_RADIO_SIZE_ANY              1185
#define IDC_RADIO_JUST_DOC              1186
#define IDC_RADIO_TOP                   1187
#define IDC_RADIO_SIZE_LARGE            1188
#define IDC_BUTTON_SOURCE               1189
#define IDC_RADIO_COLOR_ACCENTED        1190
#define IDC_BUTTON_DESTINATION          1191
#define IDC_EDIT_DEST_DIR               1192
#define IDC_RADIO_COLOR_MULTI           1193
#define IDC_CHECK_PCX                   1194
#define IDC_RADIO_COLOR_SOLID           1195
#define IDC_EDIT_STATUS                 1196
#define IDC_STATIC_TEXTURE_DIR          1197
#define IDC_BUTTON_VIEW_OPTIONS         1198
#define IDC_PROGRESS_BAR                1199
#define IDC_EDIT_STATUS_TEXT            1200
#define IDC_TEMP_STATUS                 1201
#define IDC_RADIO_UNIFORM               1202
#define IDC_RADIO_GAUSSIAN              1203
#define IDC_EDIT_WILDCARDS              1204
#define IDC_CHECK_OVERWRITE             1205
#define IDC_PALETTE                     1206
#define IDC_BUTTON_ADD                  1207
#define IDC_COLOR                       1208
#define IDC_BUTTON_QUICK_ADD            1209
#define IDC_BUTTON_LOAD                 1210
#define IDC_BUTTON_DEFAULT              1211
#define IDC_BUTTON_NEW                  1212
#define IDC_BUTTON_SAVE                 1213
#define IDC_EDIT_PALETTE_NAME           1214
#define IDC_PROGRESS1                   1215
#define IDC_PROGRESS_STATUS             1216
#define IDC_BUTTON_Q1_CUSTOM            1217
#define IDC_BUTTON_BLEND                1218
#define IDC_BUTTON_SELECT               1219
#define IDC_LIST_IMAGES                 1220
#define IDC_EDIT_OUTPUT_DIR             1221
#define IDC_BUTTON_OUTPUT_DIR           1222
#define IDC_BTN_HL_LIQUID               1223
#define IDC_BUTTON_CONVERT              1224
#define IDC_BUTTON_OPEN                 1225
#define IDC_BUTTON_IMAGE_GUI            1226
#define IDC_STATIC_INFO                 1227
#define IDC_BTN_COLOR                   1228
#define IDC_BTN_HL_TRANSPARENT          1229
#define IDC_STATIC_NAME                 1230
#define IDC_EDIT_NUMBER                 1231
#define IDC_DT1_BUTTON_PREVIEW          1232
#define IDC_RADIO_TEXTURES              1233
#define IDC_RADIO_CURRENT_PACKAGE       1234
#define IDC_STATIC_COUNT                1235
#define IDC_RADIO_NEW_PACKAGE           1236
#define IDC_BUTTON_Q2_CUSTOM            1237
#define IDC_RADIO_QUAKE2                1238
#define IDC_RADIO_RGB_VALUE             1239
#define IDC_CHECK_ALWAYS                1240
#define IDC_RADIO_PROMPT                1241
#define IDC_RADIO_HALFLIFE              1242
#define IDC_RADIO_HALFLIFE_WAD          1243
#define IDC_RADIO_QUAKE1_WAD            1244
#define IDC_STATIC_MESSAGE              1245
#define IDC_BTN_UNREAL_TRANSPARENT      1246
#define IDC_RADIO_QUAKE1                1247
#define IDC_EDIT_X_OFFSET               1248
#define IDC_EDIT_Y_OFFSET               1249
#define IDC_SPIN_X_OFFSET               1250
#define IDC_SPIN_Y_OFFSET               1251
#define IDC_BUTTON_ADVANCED             1252
#define IDC_TAB1                        1253
#define IDC_RADIO_INDEX                 1254
#define IDC_EDIT_SOURCE_INDEX           1255
#define IDC_EDIT_DEST_INDEX             1256
#define IDC_CHECK_SWAP_INDEXES          1257
#define IDC_COMBO_PALETTE               1258
#define IDC_COMBO_GROUT                 1259
#define IDC_COMBO_PACKAGE               1260
#define IDC_COMBO_BEVEL                 1261
#define IDC_COMBO_NEW_PACKAGE           1262
#define IDC_COMBO_OUTPUT_FORMAT         1263
#define IDC_COMBO_FILE_TYPE             1264
#define IDC_RADIO_DOUBLE_HEIGHT         1265
#define IDC_RADIO_HALF_HEIGHT           1266
#define IDC_RADIO_QUARTER_HEIGHT        1267
#define IDC_RADIO_QUAD_WIDTH            1268
#define IDC_RADIO_QUAD_HEIGHT           1269
#define IDC_RADIO_SINGLE_PIXEL          1270
#define IDC_RADIO_HORIZONTAL_LINE       1271
#define IDC_RADIO_VERTICAL_LINE         1272
#define IDC_EDIT_MIN_LENGTH             1273
#define IDC_EDIT_MAX_LENGTH             1274
#define IDC_RADIO_QUAD_SIZE             1275
#define IDC_RADIO_DOUBLE_SIZE           1276
#define IDC_RADIO_HALF_SIZE             1277
#define IDC_RADIO_QUARTER_SIZE          1278
#define IDC_EDIT_BLUE                   1279
#define IDC_SLIDER_GAMMA                1280
#define IDC_RADIO_SHAPE_ANY             1281
#define IDC_EDIT_GAMMA                  1282
#define IDC_RADIO_STYLE_FANCY           1283
#define IDC_RADIO_SHAPE_SQUARE          1284
#define IDC_RADIO_SIZE_SMALL            1285
#define IDC_BTN_FREE_UNDO_MEMORY        1286
#define IDC_RADIO_SIZE_MEDIUM           1287
#define IDC_RADIO_ALL_DOCS              1288
#define IDC_RADIO_DONT_DO_IT            1289
#define IDC_RADIO_UPPER_LEFT            1290
#define IDC_EDIT_SOURCE_DIR             1291
#define IDC_RADIO_COLOR_ANY             1292
#define IDC_EDIT_OFFSET                 1293
#define IDC_RADIO_ALL_EXCEPT            1294
#define IDC_CHECK_BMP                   1295
#define IDC_RADIO_COLOR_TWO             1296
#define IDC_BUTTON_DEST                 1297
#define IDC_RADIO_SIZE_TINY             1298
#define IDC_BUTTON_GO                   1299
#define IDC_RADIO_8BIT                  1300
#define IDC_RADIO_24BIT                 1301
#define IDC_RADIO2                      1302
#define IDC_RADIO_FILE                  1303
#define IDC_RADIO_NEW_WAD               1304
#define IDC_RADIO_SET_PATTERN_COLORS_FADE_IN 1305
#define IDC_RADIO_REPLACE               1306
#define IDC_CHECK_COMPRESS              1307
#define IDC_EDIT_MAX_COLORS             1308
#define IDC_EDIT_RESERVED1              1309
#define IDC_EDIT_RESERVED2              1310
#define IDC_EDIT_HORIZONTAL             1311
#define IDC_EDIT_VERTICAL               1312
#define IDC_BTN_EVERY_1                 1313
#define IDC_BTN_EVERY_2                 1314
#define IDC_BTN_EVERY_4                 1315
#define IDC_BTN_EVERY_8                 1316
#define IDC_BTN_EVERY_16                1317
#define IDC_BTN_EVERY_32                1318
#define IDC_BTN_EVERY_64                1319
#define IDC_BTN_EVERY_10                1320
#define IDC_BTN_EVERY_12                1321
#define IDC_STATIC_EVERY_H              1322
#define IDC_STATIC_EVERY_V              1323
#define IDC_STATIC_H_PIXELS             1324
#define IDC_STATIC_V_PIXELS             1325
#define IDC_RADIO_SET_PATTERN_SOURCE    1326
#define IDC_RADIO_SET_PATTERN_FADE      1327
#define IDC_RADIO_SOLID                 1328
#define IDC_RADIO_MERGE                 1329
#define IDC_CHECK_USE_AS_TILE           1330
#define IDC_RADIO_DRIP                  1331
#define IDC_RADIO_DISTORT               1332
#define IDC_CHECK_LIMIT_TO_SELECTION    1333
#define IDC_CHECK_255_IS_INVISIBLE      1334
#define IDC_STATIC_OFFSET_X             1335
#define IDC_STATIC_OFFSET_Y             1336
#define IDC_STATIC_AMOUNT               1337
#define IDC_CHECK_TOOL_255_INVISIBLE    1338
#define IDC_CHECK_FLIP                  1339
#define IDC_STATIC_FADE_IN              1340
#define IDC_STATIC_BMP                  1341
#define IDC_RADIO_BULLET_RIGHT          1342
#define IDC_CHECK_FILTER                1343
#define IDC_EDIT_FILTER                 1344
#define IDC_RADIO_Q1_DEFAULT            1345
#define IDC_EDIT_Q1_CUSTOM              1346
#define IDC_RADIO_Q2_DEFAULT            1347
#define IDC_EDIT_Q2_CUSTOM              1348
#define IDC_BUTTON_APPLY                1349
#define IDC_CHECK_SUMMARY               1351
#define IDC_CHECK_VERTICAL              1352
#define IDC_CHECK_NON16                 1353
#define IDC_PUSH_RANDOM                 1354
#define IDC_CHECK_CROP                  1355
#define IDC_CHK_PROPORTIAL              1356
#define IDC_CHECK_NOFILTER              1357
#define IDC_CHECK_HORIZONTAL            1358
#define IDC_DT1_BUTTON_LEFT             1359
#define IDC_DT1_BUTTON_RIGHT            1360
#define IDC_RADIO_SET_PATTERN_COLORS    1361
#define IDC_DT1_COMBO_WAD               1362
#define IDC_RADIO_Q2_CUSTOM             1363
#define IDC_RADIO_BULLET_LEFT           1364
#define IDC_SPIN_HORIZONTAL             1365
#define IDC_RADIO_Q1_CUSTOM             1366
#define IDC_RADIO_DEST_CUSTOM           1367
#define IDC_CHECK_COURSE_GRID           1368
#define IDC_RADIO_RIVET_IMAGE           1369
#define IDC_CHECK_FINE_GRID             1370
#define IDC_EDIT_RESERVED3              1371
#define IDC_EDIT_RESERVED4              1372
#define IDC_SPIN_VERTICAL               1373
#define IDC_EDIT_SOURCE_PALETTE         1374
#define IDC_RADIO_SOURCE_CURRENT        1375
#define IDC_RADIO_SOURCE_CUSTOM         1376
#define IDC_DT1_STATUS                  1377
#define IDC_STATIC_TILE                 1378
#define IDC_EDIT_TILENUM                1379
#define IDC_EDIT_XOFFSET                1380
#define IDC_EDIT_YOFFSET                1381
#define IDC_EDIT_ANIMATE_SPEED          1382
#define IDC_EDIT_PERCENT                1383
#define IDC_CHECK_RETAIN_DIRECTORY      1384
#define IDC_RADIO_SIN                   1385
#define IDC_EDIT_ANIMNAME               1386
#define IDC_RADIO_HERETIC2              1387
#define IDC_FLAGS_0X1                   1388
#define IDC_FLAGS_0X2                   1389
#define IDC_FLAGS_0X4                   1390
#define IDC_FLAGS_0X8                   1391
#define IDC_FLAGS_0X10                  1392
#define IDC_FLAGS_0X20                  1393
#define IDC_FLAGS_0X40                  1394
#define IDC_FLAGS_0X80                  1395
#define IDC_FLAGS_0X100                 1396
#define IDC_FLAGS_0X200                 1397
#define IDC_FLAGS_0X400                 1398
#define IDC_FLAGS_0X800                 1399
#define IDC_FLAGS_0X1000                1400
#define IDC_FLAGS_0X2000                1401
#define IDC_FLAGS_0X4000                1402
#define IDC_FLAGS_0X8000                1403
#define IDC_FLAGS_0X10000               1404
#define IDC_FLAGS_0X20000               1405
#define IDC_FLAGS_0X40000               1406
#define IDC_FLAGS_0X80000               1407
#define IDC_FLAGS_0X100000              1408
#define IDC_FLAGS_0X200000              1409
#define IDC_FLAGS_0X400000              1410
#define IDC_FLAGS_0X800000              1411
#define IDC_FLAGS_0X1000000             1412
#define IDC_FLAGS_0X2000000             1413
#define IDC_FLAGS_0X4000000             1414
#define IDC_FLAGS_0X8000000             1415
#define IDC_FLAGS_0X10000000            1416
#define IDC_FLAGS_0X20000000            1417
#define IDC_FLAGS_0X40000000            1418
#define IDC_FLAGS_0X80000000            1419
#define IDC_CONTENT_0X1                 1420
#define IDC_CONTENT_0X2                 1421
#define IDC_CONTENT_0X4                 1422
#define IDC_CONTENT_0X8                 1423
#define IDC_CONTENT_0X10                1424
#define IDC_CONTENT_0X20                1425
#define IDC_CONTENT_0X40                1426
#define IDC_CONTENT_0X80                1427
#define IDC_CONTENT_0X100               1428
#define IDC_CONTENT_0X200               1429
#define IDC_CONTENT_0X400               1430
#define IDC_CONTENT_0X800               1431
#define IDC_CONTENT_0X1000              1432
#define IDC_CONTENT_0X2000              1433
#define IDC_CONTENT_0X4000              1434
#define IDC_CONTENT_0X8000              1435
#define IDC_CONTENT_0X10000             1436
#define IDC_CONTENT_0X20000             1437
#define IDC_CONTENT_0X40000             1438
#define IDC_CONTENT_0X80000             1439
#define IDC_CONTENT_0X100000            1440
#define IDC_CONTENT_0X200000            1441
#define IDC_CONTENT_0X400000            1442
#define IDC_CONTENT_0X800000            1443
#define IDC_CONTENT_0X1000000           1444
#define IDC_CONTENT_0X2000000           1445
#define IDC_CONTENT_0X4000000           1446
#define IDC_CONTENT_0X8000000           1447
#define IDC_CONTENT_0X10000000          1448
#define IDC_CONTENT_0X20000000          1449
#define IDC_CONTENT_0X40000000          1450
#define IDC_CONTENT_0X80000000          1451
#define IDC_EDIT_LIGHT                  1452
#define IDC_EDIT_DIRECT                 1453
#define IDC_EDIT_COLOR_R                1454
#define IDC_EDIT_COLOR_G                1455
#define IDC_EDIT_COLOR_B                1456
#define IDC_EDIT_DIRECT_ANGLE           1457
#define IDC_EDIT_NONLIT                 1458
#define IDC_DESCRIPTION                 1459
#define IDC_EDIT_TRANSLUSCENCE          1460
#define IDC_CHECK_SOLID                 1461
#define IDC_CHECK_LAVA                  1462
#define IDC_CHECK_SLIME                 1463
#define IDC_CHECK_WATER                 1464
#define IDC_CHECK_MIST                  1465
#define IDC_CHECK_PORTAL                1466
#define IDC_CHECK_PLAYERCLIP            1467
#define IDC_CHECK_MONSTERCLIP           1468
#define IDC_CHECK_CURRENT0              1469
#define IDC_CHECK_CURRENT90             1470
#define IDC_CHECK_CURRENT180            1471
#define IDC_CHECK_CURRENT270            1472
#define IDC_CHECK_CURRENTUP             1473
#define IDC_CHECK_CURRENTDN             1474
#define IDC_CHECK_ORIGIN                1475
#define IDC_CHECK_DETAIL                1476
#define IDC_CHECK_TRANSLUCENT           1477
#define IDC_CHECK_LADDER                1478
#define IDC_CHECK_LIGHT                 1479
#define IDC_CHECK_SKY                   1480
#define IDC_CHECK_WARP                  1481
#define IDC_CHECK_NODRAW                1482
#define IDC_CHECK_HINT                  1483
#define IDC_CHECK_SKIP                  1484
#define IDC_CHECK_MASKED                1485
#define IDC_CHECK_WAVY                  1486
#define IDC_CHECK_RICOCHET              1487
#define IDC_CHECK_PRELIT                1488
#define IDC_CHECK_MIRROR                1489
#define IDC_CHECK_CONSOLE               1490
#define IDC_CHECK_USECOLOR              1491
#define IDC_CHECK_HWONLY                1492
#define IDC_CHECK_DAMAGE                1493
#define IDC_CHECK_WEAK                  1494
#define IDC_CHECK_NORMAL                1495
#define IDC_CHECK_STRONG                1496
#define IDC_CHECK_RANDOMANIMATE         1497
#define IDC_CHECK_ANIMATE               1498
#define IDC_CHECK_RANDOMTIME            1499
#define IDC_CHECK_TRANSLATE             1500
#define IDC_CHECK_NOMERGE               1501
#define IDC_SLIDER_COLOR                1502
#define IDC_LIST_RULES                  1503
#define IDC_BUTTON_EDIT                 1504
#define IDC_BUTTON_REMOVE               1505
#define IDC_EDIT_DESCRIPTION            1506
#define IDC_EDIT3                       1507
#define IDC_EDIT_MINIMUM_WIDTH          1508
#define IDC_BUTTON_ENABLE_ALL           1509
#define IDC_EDIT_MINIMUM_HEIGHT         1510
#define IDC_BUTTON_ENABLE_ALL2          1511
#define IDC_EDIT_MAXIMUM_WIDTH          1512
#define IDC_EDIT_MAXIMUM_HEIGHT         1513
#define IDC_BUTTON_FLAGS                1514
#define IDC_CHECK_OPTIONS_STRIP         1515
#define IDC_COMBO_VALUE                 1516
#define IDC_RADIO_DEST_CURRENT          1517
#define IDC_EDIT_DEST_PALETTE           1518
#define IDC_CHECK_RETAIN                1519
#define IDC_CHECK_RECURSE               1520
#define IDC_CHECK_NONLIT                1521
#define IDC_DT1_LIST_IMAGES             1522
#define IDC_CHECK_RETAIN_SETTINGS       1523
#define IDC_CHECK_CONVEYOR              1524
#define IDC_RADIO_CHANGE_NAME           1525
#define IDC_EDIT_VALUE                  1526
#define IDC_EDIT_TRANS_ANGLE            1527
#define IDC_CHECK_FENCE                 1528
#define IDC_EDIT_FRICTION               1529
#define IDC_EDIT_FRICTION2              1530
#define IDC_CHECK_AREAPORTAL            1531
#define IDC_RADIO_OUTPUT_BATCH          1532
#define IDC_EDIT_MATCH                  1533
#define IDC_CHECK_RNDTIME               1534
#define IDC_CHECK_ADDBLEND              1535
#define IDC_CHECK_DAMAGED               1536
#define IDC_CHECK_ENVMAP                1537
#define IDC_LIST_FIELDS                 1538
#define IDC_RADIO_REMOVE_CACHE          1539
#define IDC_EDIT_CACHE_GROOM            1540
#define IDC_LIST_WILDCARDS              1541
#define IDC_CURRENT_ASSOC               1542
#define IDC_STATIC_NUMITEMS             1543
#define IDC_PUSH_ANIMATE                1544
#define IDC_PAK_TREE                    1545
#define IDC_CHECK_REPLACE               1546
#define IDC_RADIO_EXP_SELECTED          1547
#define IDC_EDIT_SOURCE                 1548
#define IDC_DT2_COLOR_TOLERANCE         1549
#define IDC_DT2_COLOR_TOLERANCE_SPIN    1550
#define IDC_DT2_CT_STATIC               1551
#define IDC_DT1_BUTTON_MOUSE_GUI        1552
#define IDC_BUTTON_COLOR                1553
#define IDC_BUTTON_AUTO16               1554
#define IDC_BUTTON_CHECK_ALL            1555
#define IDC_BUTTON_SELECT_ALL           1556
#define IDC_BUTTON_AUTO                 1557
#define IDC_EDIT_DESTINATION_DIR        1558
#define IDC_BUTTON_UNCHECK_ALL          1559
#define IDC_RADIO_OUTPUT_ALT            1560
#define IDC_RADIO_DONT_REMOVE_CACHE     1561
#define IDC_RADIO_EXP_SPECIFIC          1562
#define IDC_TST_TAB                     1563
#define IDC_TST1_COMBO_WAD              1564
#define IDC_TST1_LIST_IMAGES            1565
#define IDC_TST1_BUTTON_PREVIEW         1566
#define IDC_TST1_BUTTON_MOUSE_GUI       1567
#define IDC_TST1_STATUS                 1568
#define IDC_TST2_COLOR_TOLERANCE_STATIC 1569
#define IDC_TST2_COLOR_TOLERANCE        1570
#define IDC_TST2_COLOR_TOLERANCE_SPIN   1571
#define IDC_TST2_COMBO_SIZE             1572
#define IDC_TST2_COMBO_SHAPE            1573
#define IDC_TST2_COMBO_AMOUNT           1574
#define IDC_TST2_STATIC1                1575
#define IDC_TST2_STATIC2                1576
#define IDC_TST2_STATIC3                1577
#define IDC_TST2_STATIC4                1578
#define IDC_EDIT_DEFAULT_PALETTE        1579
#define IDC_BUTTON_DEFAULT_PALETTE      1580
#define IDC_BUTTON_EDIT_PALETTE         1581
#define IDC_CHECK_BUILD_OPTIMIZED       1582
#define IDC_EDIT_HL_DIRECTORY           1583
#define IDC_BUTTON_HL_DIR               1584
#define IDC_RADIO_CLIPBOARD             1585
#define IDC_EDIT_FILE                   1586
#define IDC_BUTTON_FILE                 1587
#define IDC_RADIO_LET_ME                1588
#define IDC_LIST_WADS                   1589
#define IDC_EDIT_EXISTING_WAD           1590
#define IDC_BUTTON_EXISTING_WAD         1591
#define IDC_BUTTON_PROPERTIES           1592
#define IDC_RADIO_IGNORE                1593
#define IDC_RADIO_OVERWRITE             1594
#define IDC_RADIO_RENAME                1595
#define IDC_RADIO_EXISTING_WAD          1596
#define IDC_EDIT_WAD_FILE               1597
#define IDC_EDIT_WILDCARD               1598
#define IDC_BUTTON_WAD                  1599
#define IDC_RADIO_OPEN_WAD              1600
#define IDC_COMBO_OPEN_WAD              1601
#define IDC_STATUS                      1602
#define IDC_STATUS2                     1603
#define IDC_RADIO_ANY_SIZE              1604
#define IDC_STATIC_PIXELS_W             1605
#define IDC_STATIC_PIXELS_H             1606
#define IDC_STATIC_SCALE_X              1607
#define IDC_STATIC_SCALE_Y              1608
#define IDC_STATIC_PERCENT_X            1609
#define IDC_STATIC_PERCENT_Y            1610
#define IDC_RADIO_CROP                  1611
#define IDC_RADIO_RESIZE                1612
#define IDC_RADIO_ERROR                 1613
#define IDC_RADIO_MAINTAIN_ASPECT       1614
#define IDC_RADIO_STRETCH_TO_FIT        1615
#define IDC_CHECK_PURE_BLUE_PIXELS      1616
#define IDC_RADIO3                      1617
#define IDC_RADIO_BLEND_OVERALL_COLOR   1618
#define IDC_RADIO4                      1619
#define IDC_RADIO_BLEND_SPECIFIC_COLOR  1620
#define IDC_TREE_IMAGES                 1621
#define IDC_SLIDER_THUMBNAIL_SIZE       1622
#define IDC_STATIC_THUMB_SIZE           1623
#define ID_ZOOMVALUE_STATUSBAR          2000
#define ID_CONSTRAIN_STATUSBAR          2001
#define ID_ZOOM                         2002
#define ID_FILE_BROWSE                  2003
#define ID_VIEW_OPTIONS                 2004
#define IDS_OUT_OF_MEM                  2005
#define ID_FILE_LOAD_PALETTE            2006
#define ID_TP_DROPPER                   2007
#define ID_TP_SELECTION                 2008
#define ID_TP_PAINT                     2009
#define ID_TP_ZOOM                      2010
#define ID_TP_TILE                      2011
#define ID_TP_FLAGS                     2012
#define ID_PALETTE_COLORS               2013
#define ID_TP_ANIMATE                   2014
#define ID_FILE_IMPORT_ASNEWWAL         2015
#define ID_FILE_IMPORT_INTO             2016
#define ID_POPUP_COPY_AS_BITMAP         2017
#define ID_EDIT_PASTE_AS_NEW_IMAGE      2018
#define ID_TOOLBAR_MIP1                 2019
#define ID_TOOLBAR_MIP2                 2020
#define ID_TOOLBAR_MIP4                 2021
#define ID_TOOLBAR_MIP3                 2022
#define ID_TP_REMIP                     2023
#define ID_VIEW_REMIP_OPTIONS           2024
#define ID_FILE_SELECT_FOLDER           2025
#define ID_FILE_CONVERT                 2026
#define ID_TP_BRUSH                     2027
#define ID_TP_PENCIL                    2028
#define ID_TP_BIGBRUSH                  2029
#define ID_TP_ERASER                    2030
#define ID_TP_LIGHTEN                   2031
#define ID_TP_DARKEN                    2032
#define ID_TP_SCRATCH                   2033
#define ID_VIEW_TOOL_OPTIONS            2034
#define ID_TP_BULLET_HOLES              2035
#define ID_TP_WIDTH                     2036
#define ID_TP_AMOUNT                    2037
#define ID_TP_SHAPE                     2038
#define ID_TOOL_WIDTH                   2039
#define ID_WIDTH_2_PIXELS               2040
#define ID_WIDTH_1_PIXEL                2041
#define ID_WIDTH_3_PIXELS               2042
#define ID_WIDTH_5_PIXELS               2043
#define ID_WIDTH_7_PIXELS               2044
#define ID_WIDTH_11_PIXELS              2045
#define ID_WIDTH_15_PIXELS              2046
#define ID_WIDTH_31_PIXELS              2047
#define ID_APPLY_LEAST                  2048
#define ID_APPLY_A_LITTLE_BIT           2049
#define ID_APPLY_MEDIUM                 2050
#define ID_APPLY_MORE                   2051
#define ID_APPLY_MOST                   2052
#define ID_TP_TINT                      2053
#define ID_SHAPE_SQUARE                 2054
#define ID_TOOL_SHAPE                   2055
#define ID_SHAPE_CIRCULAR               2056
#define ID_SHAPE_DIAMOND                2057
#define ID_TOOL_AMOUNT                  2058
#define ID_BRPOPUP_PROPERTIES           2059
#define ID_BRPOPUP_OPEN                 2060
#define ID_TESTPPAGE                    2061
#define ID_FILE_EXPORT                  2062
#define ID_TP_REPLACE                   2063
#define ID_BUTTON32889                  2064
#define ID_TP_SPRAY                     2065
#define ID_FILTER_BLEND                 2066
#define ID_FILTER_BLEND_HEAVY           2067
#define ID_FILTER_BLEND_LIGHT           2068
#define ID_BRPOPUP_COPY                 2069
#define ID_EDIT_COPYTILED               2070
#define ID_TP_FLOOD_FILL                2071
#define ID_TP_PATTERNED_PAINT           2072
#define ID_IMAGE_MIRROR                 2073
#define ID_BRPOPUP_COPYTILED            2074
#define ID_IMAGE_FLIP                   2075
#define ID_IMAGE_ROTATE                 2076
#define ID_TP_RECOLOR                   2077
#define ID_TP_SPRAY_RECOLOR             2078
#define ID_DRAWINGMODE_FREEHAND         2079
#define ID_DRAWINGMODE_LINE             2080
#define ID_DRAWINGMODE_POLYLINE         2081
#define ID_DRAWINGMODE_RAY              2082
#define ID_DRAWINGMODE_HOLLOW_RECT      2083
#define ID_DRAWINGMODE_SOLID_RECT       2084
#define ID_DRAWINGMODE_EDGED_RECT       2085
#define ID_IMAGE_BRIGHTNESS_CONTRAST    2086
#define ID_IMAGE_ADD_NOISE              2087
#define ID_IMAGE_BLEND                  2088
#define ID_IMAGE_EMBOSS                 2089
#define ID_IMAGE_EDGE_DETECT            2090
#define ID_IMAGE_GENERATE_MARBLE_TEXTURE 2091
#define ID_IMAGE_CONVERT_TEXTURES_QUAKE_TO_FROM_UNREAL 2092
#define ID_IMAGE_GENERATE_MARBLE_TILE_TEXTURE 2093
#define ID_EDIT_FREEUNDOMEMORY          2094
#define ID_IMAGE_DIFFUSE                2095
#define ID_IMAGE_FLIP_HORZ              2096
#define ID_IMAGE_FLIP_VERT              2097
#define ID_FILE_BATCH_CONVERSION        2098
#define ID_TP_RIVETS                    2099
#define ID_EDIT_PASTE_PACKAGE           2100
#define ID_PACKAGE_OPEN                 2101
#define ID_MENUITEM2943                 2102
#define ID_EDIT_RENAME                  2103
#define ID_POPUP_DELETE                 2104
#define ID_PACKAGE_ADD                  2105
#define ID_EDIT_PASTE_OVER              2106
#define ID_EDIT_DELETE                  2107
#define ID_PACKAGE_EXPORT               2108
#define ID_IMAGE_OFFSET                 2109
#define ID_IMAGE_SHARPEN                2110
#define ID_COLORS_SWAP_INDEXES          2111
#define ID_COLORS_EDIT_PALETTE          2112
#define ID_COLORS_LOAD_PALETTE          2113
#define ID_COLORS_SAVE_PALETTE          2114
#define ID_COLORS_COUNT_COLORS_USED     2115
#define ID_COLORS_TRANSLATE             2116
#define ID_IMAGE_RESIZE                 2117
#define ID_SELECTION_SELECTALL          2118
#define ID_SELECTION_SELECTNONE         2119
#define ID_SELECTION_SELECT_NONE        2120
#define ID_SELECTION_SELECT_ALL         2121
#define ID_IMAGE_REDUCECOLORS           2122
#define ID_IMAGE_REDUCE_COLORS          2123
#define ID_REPEAT_FILTER_PICK0          2124
#define ID_REPEAT_FILTER_PICK1          2125
#define ID_REPEAT_FILTER_PICK2          2126
#define ID_REPEAT_FILTER_PICK3          2127
#define ID_SHOW_FINE_GRID               2128
#define ID_SHOW_COURSE_GRID             2129
#define ID_TOOLBAR_FINEGRID             2130
#define ID_BUTTON2974                   2131
#define ID_FILE_LOAD_Q2PALETTE          2132
#define ID_FILE_LOAD_Q1PALETTE          2133
#define ID_VIEW_DECAL                   2134
#define ID_EDIT_PASTE_SPECIALEFFECTS    2135
#define ID_PACKAGE_DRAG_COPY            2136
#define ID_PACKAGE_DRAG_MOVE            2137
#define ID_PACKAGE_DRAG_CANCEL          2138
#define ID_USE_AS_RIVET_SOURCE          2139
#define ID_USE_AS_LEFT_BULLET_SOURCE    2140
#define ID_USE_AS_RIGHT_BULLET_SOURCE   2141
#define ID_USE_AS_LEFT_PATTERN_SOURCE   2142
#define ID_USE_AS_RIGHT_PATTERN_SOURCE  2143
#define ID_TP_DECAL                     2144
#define ID_USE_AS_LEFT_DECAL_SOURCE     2145
#define ID_USE_AS_RIGHT_DECAL_SOURCE    2146
#define ID_ACCEL2991                    2147
#define ID_PACKAGE_REMIP_SELECTED       2148
#define ID_PACKAGE_REMIP_ALL            2149
#define ID_BUILD_POPUP_COPY             2150
#define ID_BUILDVIEW_POPUP_COPYTILED    2151
#define ID_BUILDVIEW_POPUP_COPY         2152
#define ID_BUILDVIEW_PROPERTIES         2153
#define ID_BUILDVIEW_POPUP_PROPERTIES   2154
#define ID_BUILDVIEW_POPUP_PASTE        2155
#define ID_BUILDVIEW_POPUP_DELETE       2156
#define ID_FILE_WLY                     2157
#define ID_PACKAGE_NEW_IMAGE            2158
#define ID_ACCEL3003                    2159
#define ID_TP_BLEND                     2160
#define ID_FILE_BROWSE2                 2161
#define ID_POPUP_COPYRESIZE             2162
#define ID_VIEW_SHOWSUBMIPS             2163
#define ID_FILE_REFRESH                 2164
#define ID_VIEW_RULES                   2165
#define ID_FILE_TEST_TXL                2166
#define ID_BVPOPUP_INFO                 2167
#define ID_BVPOPUP_DELETE               2168
#define ID_BVPOPUP_COPY_CLIPBOARD       2169
#define ID_BVPOPUP_COPY                 2170
#define ID_BVPOPUP_PASTE                2171
#define ID_IMAGE_ENLARGE                2172
#define ID_ACCEL3017                    2173
#define ID_FILE_TEST                    2174
#define ID_ACCEL3020                    2175
#define ID_FILE_BUGFIX                  2176
#define ID_TP_CLONE                     2177
#define ID_TP_RUBBER_STAMP              2178
#define ID_FILE_PAK                     2179
#define ID_PAKPOPUP_DELETE              2180
#define ID_PAKPOPUP_COPY                2181
#define ID_PAKPOPUP_PASTE               2182
#define ID_PAK_POPUP_OPEN               2183
#define ID_PAK_POPUP_DELETE             2184
#define ID_PAK_POPUP_CUT                2185
#define ID_PAK_POPUP_COPY               2186
#define ID_PAK_POPUP_RENAME             2187
#define ID_PAK_POPUP_PASTE              2188
#define ID_PAK_POPUP_NEW_FOLDER         2189
#define ID_PAK_POPUP_NEW_TXTFILE        2190
#define ID_PAK_POPUP_NEW_IMAGE          2191
#define ID_PAK_PLAYSOUND                2192
#define ID_PAK_POPUP_EXPORT             2193
#define ID_PAK_POPUP_IMPORT             2194
#define ID_FILE_DEBUG                   2195
#define ID_PACKAGE_RESIZE               2196
#define ID_WIZARD_COLOR_DECAL           2197
#define ID_WIZARD_WADMERGE              2198
#define ID_IMAGE_TILED_TINT             2199
#define ID_IMAGE_FIX_UNEVEN_LIGHTING    2200
#define ID_WIZARD_TEST                  2201
#define IDS_DEFAULT_PALETTE_FILE        11000
#define IDS_DEFAULT_Q2PALETTE_FILE      11001
#define IDS_DEFAULT_PALETTE_WILDCARD    11002
#define IDS_PALETTE_OFN_TITLE           11003
#define IDS_IMPORT_IMAGE_TITLE          11004
#define IDS_IMPORT_IMAGE_WILDCARD       11005
#define ID_ZOOM_DIALOGBAR               11006
#define ID_XYPOS                        11007
#define ID_WIDTH_HEIGHT                 11008
#define ID_BLANK_PANE                   11009
#define ID_BROWSE_BLANK                 11010
#define IDS_FILEOPEN_WILDCARD           11011
#define IDS_FILEOPEN_TITLE              11012
#define IDS_FILEOPEN_EXTENSION          11013
#define IDS_FILEBROWSE_TITLE            11014
#define IDS_FILE_CONVERT_WILDCARD       11015
#define IDS_DEFAULT_Q1PALETTE_FILE      11016
#define IDS_FILESAVE_TITLE              11017
#define IDS_FILEEXPORT_TITLE            11018
#define IDS_FILE_EXPORT_WILDCARD        11019
#define ID_IMAGE_EDIT_TOOLBAR           32000
#define ID_MODES_TOOLBAR                32001
#define ID_PALETTE_TOOLBAR              32002
#define ID_TOOLSETTINGS_TOOLBAR         32003
#define IDS_WAD3_PACKAGE                61000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        271
#define _APS_NEXT_COMMAND_VALUE         2202
#define _APS_NEXT_CONTROL_VALUE         1625
#define _APS_NEXT_SYMED_VALUE           268
#endif
#endif
