//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wally.rc
//
#define ID_FILTER_PREVIEW               3
#define ID_FILTER_APPLY                 4
#define IDD_ABOUTBOX                    100
#define CG_IDR_POPUP_WALLY_VIEW         102
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    103
#define IDD_DIALOGBAR_ZOOM              103
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 104
#define IDB_SPLASH                      105
#define CG_IDR_POPUP_BROWSE_VIEW        106
#define IDS_PROPSHT_CAPTION             107
#define IDD_PROPPAGE1                   108
#define IDD_PROPPAGE2                   109
#define ID_EDIT_ZOOMIN                  110
#define ID_EDIT_ZOOMOUT                 111
#define ID_EDIT_SHIFT_LEFT              112
#define ID_EDIT_SHIFT_RIGHT             113
#define ID_EDIT_SHIFT_UP                114
#define ID_EDIT_SHIFT_DOWN              115
#define ID_STATUSBAR_PROGRESS           119
#define IDR_MAINFRAME                   127
#define IDR_WALLYTYPE                   128
#define IDR_PACKAGE_TYPE                129
#define IDR_BROWSETYPE                  130
#define IDR_BUILDTYPE                   131
#define IDR_PACKAGE_VIEW_TYPE           132
#define IDR_BROWSE2TYPE                 133
#define IDR_PAK_TYPE                    134
#define IDR_WLY_TYPE                    135
#define CG_IDR_POPUP_SHAPE              136
#define IDD_TEXTURE_INFO                137
#define CG_IDR_POPUP_DRAWING_WIDTH      138
#define CG_IDR_POPUP_AMOUNT             139
#define IDR_IMAGE_EDIT_TOOLBAR          140
#define IDR_MODES_TOOLBAR               141
#define IDD_NEW_WAL                     142
#define IDD_NEW_TEXTURE_DLG1            147
#define IDC_ZOOM_CURSOR                 148
#define IDC_PAINT_CURSOR                149
#define IDC_DROPPER_CURSOR              150
#define IDD_PALETTE_MISMATCH            156
#define IDD_WALLY_OPTIONS               157
#define IDD_REMIP_DLG                   161
#define IDD_TOOL_OPTIONS_DLG            162
#define IDB_REMIP                       164
#define IDB_OPTIONS                     165
#define IDD_PALETTE_TOOLBAR             166
#define IDD_COPYTILED                   167
#define IDB_BRUSH_SIZE                  170
#define IDB_BRUSH_SHAPE                 171
#define IDB_AMOUNT                      172
#define IDD_ROTATE                      173
#define IDD_EDGE_DETECT_DLG             174
#define IDI_ICON1                       175
#define IDI_WALLY_ICON                  175
#define IDD_BROWSE_DLG                  176
#define IDD_BATCH_DLG                   177
#define IDD_ADD_NOISE_DLG               178
#define IDD_BLEND_DLG                   179
#define IDD_BRIGHTNESS_CONTRAST_DLG     180
#define IDD_EMBOSS_DLG                  181
#define IDD_MARBLE_DLG                  182
#define IDD_UNREAL_DLG                  183
#define IDD_PALETTE_PICKER_DLG          184
#define IDD_MARBLE_TILE_DLG             185
#define IDD_FREE_UNDOS_DLG              188
#define IDD_DIFFUSE_DLG                 189
#define IDD_MIRROR_DLG                  190
#define IDD_BATCHTEMP_DLG               191
#define IDD_BC_SUMMARY_DLG              193
#define IDD_NEW_IMAGE_DLG               195
#define IDD_HALF_LIFE_PALETTE_DLG       196
#define IDD_NEW_PALETTE_DLG             198
#define IDD_PALETTE_NAME_DLG            199
#define IDD_WADPAK_VIEW_DLG             201
#define IDD_RENAME_IMAGE_DLG            204
#define IDR_PACKAGE_POPUP               205
#define IDD_ADDTO_PACKAGE_DLG           206
#define IDD_PACKAGE_CONVERT_DLG         207
#define IDD_PACKAGE_EXPORT_DLG          207
#define IDD_JUST_FOR_TESTING            208
#define IDD_SELECT_GAME_DLG             212
#define IDD_PROPPAGE3                   213
#define IDB_WALLYDOC_ICONS              214
#define IDD_DUPLICATE_NAME              215
#define IDD_OFFSET_DLG                  216
#define IDD_SHARPEN_DLG                 217
#define IDD_PALETTE_EDITOR_DLG          218
#define IDD_COLOR_TRANSLATOR_DLG        220
#define IDD_RESIZE_DLG                  221
#define IDD_REDUCE_COLORS_DLG           222
#define IDB_BITMAP1                     222
#define IDD_PROPPAGE4                   223
#define IDB_BMP_MASK                    224
#define IDD_PASTE_SPECIAL               225
#define IDB_PACKAGEDOC_ICONS            226
#define IDB_SPLASH_ON                   227
#define IDR_WAVE_FIRE                   228
#define IDR_PACKAGE_DRAG_POPUP          229
#define IDD_PROPPAGE5                   230
#define IDB_GRID                        231
#define IDB_PALETTE                     232
#define IDB_NEWTEXS                     233
#define IDR_WAVE_HUM                    234
#define IDD_DECAL_TOOLBAR               235
#define IDD_DECAL_TOOLBAR_PAGE1         236
#define IDD_BATCH_ADV_DLG               237
#define IDR_PCX_MOUSE                   239
#define IDR_PCX_MOUSE_L                 240
#define IDR_PCX_MOUSE_LRX               242
#define IDR_PCX_MOUSE_R                 243
#define IDR_PCX_MOUSE_RX                244
#define IDR_PCX_MOUSE_X                 245
#define IDR_LMP_DUKE3D                  251
#define IDR_LMP_SHADOW                  252
#define IDR_LMP_REDNECK                 253
#define IDR_BUILDVIEW_POPUP             254
#define IDD_BUILD_PROPERTIES_DLG        255
#define IDD_GAME_PALETTE_DLG            256
#define IDR_LMP_QUAKE1                  258
#define IDR_LMP_QUAKE2                  259
#define IDR_PCX_BUILDVIEW_BUTTON        260
#define IDD_NEW_PACKAGE_IMAGE           263
#define IDD_PERCENT_DLG                 264
#define IDR_PCX_WAD_THUMB               269
#define IDD_BATCH_ADV_PAGE1             270
#define IDD_BATCH_ADV_PAGE2             271
#define IDD_PROPPAGE6                   272
#define IDD_SIN_FLAGS_DLG               274
#define IDD_DIALOG2                     275
#define IDD_RULES_DLG                   277
#define IDD_DIALOG1                     278
#define IDD_NEW_RULE_DLG                278
#define IDD_SIN_RULE_FLAGS_DLG          279
#define IDR_BROWSE2_POPUP               280
#define IDR_BROWSE_POPUP                280
#define IDD_ENLARGE_CANVAS_DLG          281
#define IDD_PROPPAGE7                   282
#define IDR_PACKAGE_BROWSE_POPUP        285
#define IDB_PUSH_RANDOM                 286
#define IDB_PUSH_ANIMATE                287
#define IDB_PUSH_TILE_MODE              288
#define IDB_PUSH_BROWSE_MODE            289
#define IDR_PAK_POPUP                   292
#define IDD_PAK_IMPORT_DLG              294
#define IDD_PAK_TREE_DLG                295
#define IDD_PAK_EXPORT_DLG              296
#define IDD_DECAL_TOOLBAR_PAGE2         297
#define IDD_TOOL_SETTINGS_TOOLBAR       298
#define IDD_TOOL_SETTINGS_PAGE1         299
#define IDD_TOOL_SETTINGS_PAGE2         300
#define IDB_REMIP_HELP                  303
#define IDB_BATCH_CONVERSION            304
#define IDB_FILE_ASSOCIATIONS           305
#define IDR_LMP_BLEND                   306
#define IDD_COLOR_DECAL                 307
#define IDB_COLOR_DECAL                 309
#define IDR_WAD_PLDECAL                 310
#define IDD_WADMERGE_DLG                311
#define IDD_WADMERGE_ADD_DLG            312
#define IDD_WAD_MERGE_STATUS            313
#define IDR_TEX_TYPE                    314
#define IDD_FIX_UNEVEN_LIGHTING_DLG     314
#define IDR_PCX_WALLY_LOGO              315
#define IDC_MOVE_CURSOR                 317
#define IDC_HAND_CURSOR                 318
#define IDB_PACKAGE_TREE_IMAGE          319
#define IDR_DEFAULT_PALETTE				320
#define IDC_TEXTURE_NAME                1000
#define IDC_WIDTH                       1001
#define IDC_HEIGHT                      1002
#define IDC_VALUE                       1003
#define IDC_ANIMNAME                    1004
#define IDC_WINDOW_CHECK                1008
#define IDC_CHECK_AUTO_REMIP            1009
#define IDC_CHECK_WINDOW                1009
#define IDC_LIGHT_CHECK                 1010
#define IDC_SLICK_CHECK                 1011
#define IDC_WARP_CHECK                  1012
#define IDC_TRANS33_CHECK               1013
#define IDC_TRANS66_CHECK               1014
#define IDC_FLOWING_CHECK               1015
#define IDC_NODRAW_CHECK                1016
#define IDC_LAVA_CHECK                  1017
#define IDC_SLIME_CHECK                 1018
#define IDC_WATER_CHECK                 1019
#define IDC_MIST_CHECK                  1020
#define IDC_EDIT_WIDTH                  1021
#define IDC_SPIN_HEIGHT                 1022
#define IDC_NEW_PALETTE                 1023
#define IDC_CONVERT_PALETTE             1024
#define IDC_NEAREST_COLOR               1025
#define IDC_INDEXED                     1026
#define IDC_PORTAL_CHECK                1027
#define IDC_EDIT_MAX_THREADS            1027
#define IDC_COMBO_TINT                  1028
#define IDC_CHECK4                      1029
#define IDC_SPIN_MAXTHREADS             1029
#define IDC_HINT_CHECK                  1029
#define IDC_PUSH_BROWSE_MODE            1029
#define IDC_TRANSLUCENT_CHECK           1030
#define IDC_EDIT_ZOOMVALUE              1031
#define IDC_SPIN_ZOOMVALUE              1032
#define IDC_CURRENTDN_CHECK             1033
#define IDC_PLAYERCLIP_CHECK            1034
#define IDC_MONSTERCLIP_CHECK           1035
#define IDC_CURRENT0_CHECK              1036
#define IDC_CURRENT90_CHECK             1037
#define IDC_CURRENT180_CHECK            1038
#define IDC_CURRENT270_CHECK            1039
#define IDC_CURRENTUP_CHECK             1040
#define IDC_SPIN_MAX_ITEMS              1041
#define IDC_ORIGIN_CHECK                1042
#define IDC_RADIO_LEFT                  1043
#define IDC_RADIO_RIGHT                 1044
#define IDC_DETAIL_CHECK                1045
#define IDC_LADDER_CHECK                1047
#define IDC_SKIP_CHECK                  1048
#define IDC_BTN_USE_RECOMMENDED         1049
#define IDC_BTN_USE_QUAKE               1050
#define IDC_RADIO_ERROR_DIFUSSION       1051
#define IDC_RADIO_WHITE_NOISE           1052
#define IDC_RADIO_NO_DITHER             1053
#define IDC_RADIO_HEAVY                 1054
#define IDC_RADIO_MEDIUM                1055
#define IDC_RADIO_LIGHT                 1056
#define IDC_RADIO_NO_SHARPENING         1057
#define IDC_RADIO_DOUBLE_WIDTH          1058
#define IDC_COMBO_RBTN_SIZE             1059
#define IDC_RADIO_HALF_WIDTH            1060
#define IDC_COMBO_LIGHTEN               1061
#define IDC_COMBO_DARKEN                1062
#define IDC_COMBO_SCRATCH               1063
#define IDC_RADIO_PALETTE_MAINTAIN      1064
#define IDC_RADIO_PALETTE_NEAREST       1065
#define IDC_STATIC_WIDTH                1066
#define IDC_STATIC_HEIGHT               1067
#define IDC_CHECK_AUTO_REMIP2           1068
#define IDC_SKY_CHECK                   1069
#define IDC_CHECK_USE_WEIGHTED          1070
#define IDC_CHECK_RETAIN_SIZE           1071
#define IDC_SOLID_CHECK                 1072
#define IDC_CHECK_REBUILD_SUBMIPS       1073
#define IDC_RADIO_WHITE                 1074
#define IDC_AUX_CHECK                   1075
#define IDC_RADIO_QUARTER_WIDTH         1076
#define IDC_EDIT_NAME                   1077
#define IDC_SPIN_WIDTH                  1078
#define IDC_COMBO1                      1079
#define IDC_COMBO_IMAGE_TYPE            1079
#define IDC_COMBO_ANIMATE_TYPE          1079
#define IDC_COMBO_GAME                  1079
#define IDC_COMBO_SURFACE_TYPE          1079
#define IDC_COMBO_GAMETYPE              1079
#define IDC_TST2_COMBO_ZOOM             1079
#define IDC_COMBO_MOD                   1079
#define IDC_COMBO_WAD_TYPE              1079
#define IDC_EDIT_HEIGHT                 1080
#define ID_COMBO_AMOUNT                 1081
#define ID_COMBO_SHAPE                  1082
#define IDC_DT_TAB                      1083
#define IDC_EDIT_WIDTH1                 1084
#define IDC_EDIT_HEIGHT1                1085
#define IDC_BTN_PALETTE                 1086
#define IDC_BTN_UI_AREA                 1087
#define IDC_CUSTOM1                     1088
#define IDC_EDIT_TILE                   1089
#define IDC_EDIT_ANIMATE_COUNT          1089
#define ID_COMBO_SIZE                   1090
#define IDC_NUMTILES_SPIN               1091
#define IDC_LEFT_RADIO                  1092
#define IDC_RIGHT_RADIO                 1093
#define IDC_90DEG_RADIO                 1094
#define IDC_180DEG_RADIO                1095
#define IDC_270DEG_RADIO                1096
#define IDC_RADIO_PRESETDIR             1097
#define IDC_RADIO_PARENTDIR             1098
#define IDC_COMBO_OUTPUT_TYPE           1099
#define IDC_EDIT_PRESETDIR              1100
#define IDC_RADIO_BLANKDIR              1101
#define IDC_EDIT_PATH                   1102
#define IDC_SELECT_BUTTON               1103
#define IDC_EDIT_MAX_ITEMS              1104
#define IDC_EDIT_BRIGHTNESS             1105
#define IDC_SPIN_BRIGHTNESS             1106
#define IDC_EDIT_CONTRAST               1107
#define IDC_EDIT_OUTPUT_FOLDER          1108
#define IDC_BUTTON_OUTPUT_FOLDER        1109
#define IDC_EDIT_FADE_IN                1109
#define IDC_RADIO_VERY_HEAVY            1110
#define IDC_SPIN_FADE_IN                1110
#define IDC_CHECK2                      1111
#define IDC_CHECK3                      1112
#define IDC_PUSH_TILE_MODE              1112
#define IDC_CHECK5                      1113
#define IDC_RADIO_VERY_LIGHT            1114
#define IDC_SPIN_CONTRAST               1115
#define IDC_CHECK_MONOCHROME            1116
#define IDC_VERY_HEAVY                  1117
#define IDC_HEAVY                       1118
#define IDC_RADIO_BLACK                 1119
#define IDC_CHECK_SEAMLESS              1120
#define IDC_BTN_JUST_DO_IT              1121
#define IDC_BTN_BACKGROUND_COLOR        1122
#define IDC_BTN_THICK_STRIPE_COLOR      1123
#define IDC_EDIT_RANDOM_SEED            1124
#define IDC_BTN_THIN_STRIPE_COLOR       1125
#define IDC_BTN_RANDOM_SEED             1126
#define IDC_EDIT_NUM_THICK_STRIPES      1127
#define IDC_SPIN_NUM_THICK_STRIPES      1128
#define IDC_CHECK_EXTRA_SMOOTH          1129
#define IDC_SPIN_AMPLITUDE              1130
#define IDC_CHECK_EXTRA_SMOOTH2         1132
#define IDC_EDIT_AMPLITUDE              1133
#define IDC_EDIT_SCALE_X                1134
#define IDC_EDIT_SCALE_Y                1135
#define IDC_EDIT_SCALE_Z                1136
#define IDC_EDIT_COLOR_VARIANCE         1137
#define IDC_EDIT_INTENSITY_VARIANCE     1138
#define IDC_EDIT_OFFSET_X               1139
#define IDC_EDIT_OFFSET_Y               1140
#define IDC_EDIT_OFFSET_Z               1141
#define IDC_EDIT_NUM_THICK_STRIPES2     1142
#define IDC_SPIN_NUM_THICK_STRIPES2     1143
#define IDC_SPIN_LEVELS                 1144
#define IDC_EDIT_LEVELS                 1145
#define IDC_EDIT_NUM_THIN_STRIPES       1146
#define IDC_SPIN_NUM_THIN_STRIPES       1147
#define IDC_SPIN_COLOR_VARIANCE         1148
#define IDC_SPIN_SCALE_X                1149
#define IDC_SPIN_SCALE_Y                1150
#define IDC_SPIN_SCALE_Z                1151
#define IDC_SPIN_OFFSET_X               1152
#define IDC_SPIN_OFFSET_Y               1153
#define IDC_SPIN_OFFSET_Z               1154
#define ID_FILTER_FAST_PREVIEW          1155
#define ID_MARBLE_PROPERTIES            1156
#define IDC_INDEX                       1157
#define IDC_RED                         1158
#define IDC_GREEN                       1159
#define IDC_BLUE                        1160
#define IDC_EDIT_INDEX                  1161
#define IDC_EDIT_RED                    1162
#define IDC_EDIT_GREEN                  1163
#define IDC_RADIO_SHAPE_RECTANGULAR     1164
#define IDC_RADIO_SHAPE_HEXAGONAL       1165
#define IDC_RADIO_SHAPE_OTHER           1166
#define IDC_BTN_GROUT_COLOR             1167
#define IDC_RADIO_STYLE_ANY             1168
#define IDC_RADIO_STYLE_PLAIN           1169
#define IDC_CHECK_GAMMA_PALETTE_TOOLBAR 1170
#define IDC_RADIO_STYLE_EXTRA_FANCY     1171
#define IDC_RADIO_SIZE_ANY              1172
#define IDC_RADIO_JUST_DOC              1173
#define IDC_RADIO_TOP                   1174
#define IDC_RADIO_SIZE_LARGE            1175
#define IDC_BUTTON_SOURCE               1176
#define IDC_RADIO_COLOR_ACCENTED        1177
#define IDC_BUTTON_DESTINATION          1177
#define IDC_EDIT_DEST_DIR               1178
#define IDC_RADIO_COLOR_MULTI           1179
#define IDC_CHECK_PCX                   1180
#define IDC_RADIO_COLOR_SOLID           1181
#define IDC_EDIT_STATUS                 1182
#define IDC_STATIC_TEXTURE_DIR          1183
#define IDC_BUTTON_VIEW_OPTIONS         1184
#define IDC_PROGRESS_BAR                1185
#define IDC_EDIT_STATUS_TEXT            1186
#define IDC_TEMP_STATUS                 1187
#define IDC_RADIO_UNIFORM               1188
#define IDC_RADIO_GAUSSIAN              1189
#define IDC_EDIT_WILDCARDS              1190
#define IDC_CHECK_OVERWRITE             1191
#define IDC_PALETTE                     1192
#define IDC_BUTTON_ADD                  1193
#define IDC_COLOR                       1194
#define IDC_BUTTON_QUICK_ADD            1194
#define IDC_BUTTON_LOAD                 1195
#define IDC_BUTTON_DEFAULT              1196
#define IDC_BUTTON_NEW                  1197
#define IDC_BUTTON_SAVE                 1198
#define IDC_EDIT_PALETTE_NAME           1199
#define IDC_PROGRESS1                   1200
#define IDC_PROGRESS_STATUS             1200
#define IDC_BUTTON_Q1_CUSTOM            1201
#define IDC_BUTTON_BLEND                1202
#define IDC_BUTTON_SELECT               1203
#define IDC_LIST_IMAGES                 1204
#define IDC_EDIT_OUTPUT_DIR             1205
#define IDC_BUTTON_OUTPUT_DIR           1206
#define IDC_BTN_HL_LIQUID               1207
#define IDC_BUTTON_CONVERT              1208
#define IDC_BUTTON_OPEN                 1209
#define IDC_BUTTON_IMAGE_GUI            1210
#define IDC_STATIC_INFO                 1212
#define IDC_BTN_COLOR                   1213
#define IDC_BTN_HL_TRANSPARENT          1214
#define IDC_STATIC_NAME                 1215
#define IDC_EDIT_NUMBER                 1216
#define IDC_DT1_BUTTON_PREVIEW          1217
#define IDC_RADIO_TEXTURES              1218
#define IDC_RADIO_CURRENT_PACKAGE       1219
#define IDC_STATIC_COUNT                1220
#define IDC_RADIO_NEW_PACKAGE           1220
#define IDC_BUTTON_Q2_CUSTOM            1221
#define IDC_RADIO_QUAKE2                1222
#define IDC_RADIO_RGB_VALUE             1223
#define IDC_CHECK_ALWAYS                1224
#define IDC_RADIO_PROMPT                1225
#define IDC_RADIO_HALFLIFE              1226
#define IDC_RADIO_HALFLIFE_WAD          1227
#define IDC_RADIO_QUAKE1_WAD            1228
#define IDC_STATIC_MESSAGE              1229
#define IDC_BTN_UNREAL_TRANSPARENT      1230
#define IDC_RADIO_QUAKE1                1231
#define IDC_EDIT_X_OFFSET               1232
#define IDC_EDIT_Y_OFFSET               1233
#define IDC_SPIN_X_OFFSET               1234
#define IDC_SPIN_Y_OFFSET               1235
#define IDC_BUTTON_ADVANCED             1236
#define IDC_TAB1                        1237
#define IDC_RADIO_INDEX                 1238
#define IDC_EDIT_SOURCE_INDEX           1239
#define IDC_EDIT_DEST_INDEX             1240
#define IDC_CHECK_SWAP_INDEXES          1241
#define IDC_COMBO_PALETTE               1242
#define IDC_COMBO_GROUT                 1243
#define IDC_COMBO_PACKAGE               1244
#define IDC_COMBO_BEVEL                 1245
#define IDC_COMBO_NEW_PACKAGE           1245
#define IDC_COMBO_OUTPUT_FORMAT         1246
#define IDC_COMBO_FILE_TYPE             1247
#define IDC_RADIO_DOUBLE_HEIGHT         1249
#define IDC_RADIO_HALF_HEIGHT           1250
#define IDC_RADIO_QUARTER_HEIGHT        1251
#define IDC_RADIO_QUAD_WIDTH            1252
#define IDC_RADIO_QUAD_HEIGHT           1253
#define IDC_RADIO_SINGLE_PIXEL          1254
#define IDC_RADIO_HORIZONTAL_LINE       1255
#define IDC_RADIO_VERTICAL_LINE         1256
#define IDC_EDIT_MIN_LENGTH             1257
#define IDC_EDIT_MAX_LENGTH             1258
#define IDC_RADIO_QUAD_SIZE             1259
#define IDC_RADIO_DOUBLE_SIZE           1260
#define IDC_RADIO_HALF_SIZE             1261
#define IDC_RADIO_QUARTER_SIZE          1262
#define IDC_EDIT_BLUE                   1263
#define IDC_SLIDER_GAMMA                1264
#define IDC_RADIO_SHAPE_ANY             1265
#define IDC_EDIT_GAMMA                  1266
#define IDC_RADIO_STYLE_FANCY           1267
#define IDC_RADIO_SHAPE_SQUARE          1268
#define IDC_RADIO_SIZE_SMALL            1269
#define IDC_BTN_FREE_UNDO_MEMORY        1270
#define IDC_RADIO_SIZE_MEDIUM           1271
#define IDC_RADIO_ALL_DOCS              1272
#define IDC_RADIO_DONT_DO_IT            1273
#define IDC_RADIO_UPPER_LEFT            1274
#define IDC_EDIT_SOURCE_DIR             1275
#define IDC_RADIO_COLOR_ANY             1276
#define IDC_EDIT_OFFSET                 1276
#define IDC_RADIO_ALL_EXCEPT            1277
#define IDC_CHECK_BMP                   1278
#define IDC_RADIO_COLOR_TWO             1279
#define IDC_BUTTON_DEST                 1280
#define IDC_RADIO_SIZE_TINY             1281
#define IDC_BUTTON_GO                   1282
#define IDC_RADIO_8BIT                  1283
#define IDC_RADIO_24BIT                 1284
#define IDC_RADIO2                      1285
#define IDC_RADIO_FILE                  1285
#define IDC_RADIO_NEW_WAD               1285
#define IDC_RADIO_SET_PATTERN_COLORS_FADE_IN 1286
#define IDC_RADIO_REPLACE               1287
#define IDC_CHECK_COMPRESS              1288
#define IDC_EDIT_MAX_COLORS             1289
#define IDC_EDIT_RESERVED1              1290
#define IDC_EDIT_RESERVED2              1291
#define IDC_EDIT_HORIZONTAL             1292
#define IDC_EDIT_VERTICAL               1293
#define IDC_BTN_EVERY_1                 1294
#define IDC_BTN_EVERY_2                 1295
#define IDC_BTN_EVERY_4                 1296
#define IDC_BTN_EVERY_8                 1297
#define IDC_BTN_EVERY_16                1298
#define IDC_BTN_EVERY_32                1299
#define IDC_BTN_EVERY_64                1300
#define IDC_BTN_EVERY_10                1301
#define IDC_BTN_EVERY_12                1302
#define IDC_STATIC_EVERY_H              1303
#define IDC_STATIC_EVERY_V              1304
#define IDC_STATIC_H_PIXELS             1305
#define IDC_STATIC_V_PIXELS             1306
#define IDC_RADIO_SET_PATTERN_SOURCE    1307
#define IDC_RADIO_SET_PATTERN_FADE      1308
#define IDC_RADIO_SOLID                 1309
#define IDC_RADIO_MERGE                 1310
#define IDC_CHECK_USE_AS_TILE           1311
#define IDC_RADIO_DRIP                  1312
#define IDC_RADIO_DISTORT               1313
#define IDC_CHECK_LIMIT_TO_SELECTION    1314
#define IDC_CHECK_255_IS_INVISIBLE      1315
#define IDC_STATIC_OFFSET_X             1316
#define IDC_STATIC_OFFSET_Y             1317
#define IDC_STATIC_AMOUNT               1318
#define IDC_CHECK_TOOL_255_INVISIBLE    1319
#define IDC_CHECK_FLIP                  1320
#define IDC_STATIC_FADE_IN              1321
#define IDC_STATIC_BMP                  1322
#define IDC_RADIO_BULLET_RIGHT          1323
#define IDC_CHECK_FILTER                1324
#define IDC_EDIT_FILTER                 1325
#define IDC_RADIO_Q1_DEFAULT            1326
#define IDC_EDIT_Q1_CUSTOM              1327
#define IDC_RADIO_Q2_DEFAULT            1328
#define IDC_EDIT_Q2_CUSTOM              1329
#define IDC_BUTTON_APPLY                1330
#define IDC_CHECK1                      1331
#define IDC_CHECK_SUMMARY               1331
#define IDC_CHECK_VERTICAL              1331
#define IDC_CHECK_NON16                 1331
#define IDC_PUSH_RANDOM                 1331
#define IDC_CHECK_CROP                  1331
#define IDC_CHK_PROPORTIAL              1331
#define IDC_CHECK_NOFILTER              1332
#define IDC_CHECK_HORIZONTAL            1332
#define IDC_DT1_BUTTON_LEFT             1333
#define IDC_DT1_BUTTON_RIGHT            1334
#define IDC_RADIO_SET_PATTERN_COLORS    1335
#define IDC_DT1_COMBO_WAD               1336
#define IDC_RADIO_Q2_CUSTOM             1337
#define IDC_RADIO_BULLET_LEFT           1338
#define IDC_SPIN_HORIZONTAL             1339
#define IDC_RADIO_Q1_CUSTOM             1340
#define IDC_RADIO_DEST_CUSTOM           1341
#define IDC_CHECK_COURSE_GRID           1342
#define IDC_RADIO_RIVET_IMAGE           1343
#define IDC_CHECK_FINE_GRID             1344
#define IDC_EDIT_RESERVED3              1345
#define IDC_EDIT_RESERVED4              1346
#define IDC_SPIN_VERTICAL               1347
#define IDC_EDIT_SOURCE_PALETTE         1348
#define IDC_RADIO_SOURCE_CURRENT        1349
#define IDC_RADIO_SOURCE_CUSTOM         1350
#define IDC_DT1_STATUS                  1351
#define IDC_STATIC_TILE                 1352
#define IDC_EDIT_TILENUM                1354
#define IDC_EDIT_XOFFSET                1355
#define IDC_EDIT_YOFFSET                1356
#define IDC_EDIT_ANIMATE_SPEED          1357
#define IDC_EDIT_PERCENT                1357
#define IDC_CHECK_RETAIN_DIRECTORY      1360
#define IDC_RADIO_SIN                   1361
#define IDC_EDIT_ANIMNAME               1362
#define IDC_RADIO_HERETIC2              1362
#define IDC_EDIT_LIGHT                  1363
#define IDC_EDIT_DIRECT                 1364
#define IDC_EDIT_COLOR_R                1366
#define IDC_EDIT_COLOR_G                1367
#define IDC_EDIT_COLOR_B                1368
#define IDC_EDIT_DIRECT_ANGLE           1369
#define IDC_EDIT_NONLIT                 1370
#define IDC_DESCRIPTION                 1371
#define IDC_EDIT_TRANSLUSCENCE          1372
#define IDC_CHECK_SOLID                 1373
#define IDC_CHECK_LAVA                  1374
#define IDC_CHECK_SLIME                 1375
#define IDC_CHECK_WATER                 1376
#define IDC_CHECK_MIST                  1377
#define IDC_CHECK_PORTAL                1378
#define IDC_CHECK_PLAYERCLIP            1379
#define IDC_CHECK_MONSTERCLIP           1380
#define IDC_CHECK_CURRENT0              1381
#define IDC_CHECK_CURRENT90             1382
#define IDC_CHECK_CURRENT180            1383
#define IDC_CHECK_CURRENT270            1384
#define IDC_CHECK_CURRENTUP             1385
#define IDC_CHECK_CURRENTDN             1386
#define IDC_CHECK_ORIGIN                1387
#define IDC_CHECK_DETAIL                1388
#define IDC_CHECK_TRANSLUCENT           1389
#define IDC_CHECK_LADDER                1390
#define IDC_CHECK_LIGHT                 1391
#define IDC_CHECK_SKY                   1392
#define IDC_CHECK_WARP                  1393
#define IDC_CHECK_NODRAW                1394
#define IDC_CHECK_HINT                  1395
#define IDC_CHECK_SKIP                  1396
#define IDC_CHECK_MASKED                1397
#define IDC_CHECK_WAVY                  1398
#define IDC_CHECK_RICOCHET              1399
#define IDC_CHECK_PRELIT                1400
#define IDC_CHECK_MIRROR                1401
#define IDC_CHECK_CONSOLE               1402
#define IDC_CHECK_USECOLOR              1403
#define IDC_CHECK_HWONLY                1404
#define IDC_CHECK_DAMAGE                1405
#define IDC_CHECK_WEAK                  1406
#define IDC_CHECK_NORMAL                1407
#define IDC_CHECK_STRONG                1408
#define IDC_CHECK_RANDOMANIMATE         1409
#define IDC_CHECK_ANIMATE               1410
#define IDC_CHECK_RANDOMTIME            1411
#define IDC_CHECK_TRANSLATE             1412
#define IDC_CHECK_NOMERGE               1413
#define IDC_SLIDER_COLOR                1414
#define IDC_LIST_RULES                  1415
#define IDC_BUTTON_EDIT                 1416
#define IDC_BUTTON_REMOVE               1417
#define IDC_EDIT_DESCRIPTION            1418
#define IDC_EDIT3                       1420
#define IDC_EDIT_MINIMUM_WIDTH          1420
#define IDC_BUTTON_ENABLE_ALL           1421
#define IDC_EDIT_MINIMUM_HEIGHT         1421
#define IDC_BUTTON_ENABLE_ALL2          1422
#define IDC_EDIT_MAXIMUM_WIDTH          1422
#define IDC_EDIT_MAXIMUM_HEIGHT         1423
#define IDC_BUTTON_FLAGS                1426
#define IDC_CHECK_OPTIONS_STRIP         1427
#define IDC_COMBO_VALUE                 1429
#define IDC_RADIO_DEST_CURRENT          1430
#define IDC_EDIT_DEST_PALETTE           1431
#define IDC_CHECK_RETAIN                1432
#define IDC_CHECK_RECURSE               1433
#define IDC_CHECK_NONLIT                1434
#define IDC_DT1_LIST_IMAGES             1435
#define IDC_CHECK_RETAIN_SETTINGS       1436
#define IDC_CHECK_CONVEYOR              1437
#define IDC_RADIO_CHANGE_NAME           1438
#define IDC_EDIT_VALUE                  1439
#define IDC_EDIT_TRANS_ANGLE            1440
#define IDC_CHECK_FENCE                 1441
#define IDC_EDIT_FRICTION               1442
#define IDC_EDIT_FRICTION2              1443
#define IDC_CHECK_AREAPORTAL            1444
#define IDC_RADIO_OUTPUT_BATCH          1445
#define IDC_EDIT_MATCH                  1446
#define IDC_CHECK_RNDTIME               1447
#define IDC_CHECK_ADDBLEND              1448
#define IDC_CHECK_DAMAGED               1449
#define IDC_CHECK_ENVMAP                1449
#define IDC_LIST_FIELDS                 1450
#define IDC_RADIO_REMOVE_CACHE          1452
#define IDC_EDIT_CACHE_GROOM            1453
#define IDC_LIST_WILDCARDS              1456
#define IDC_CURRENT_ASSOC               1457
#define IDC_STATIC_NUMITEMS             1460
#define IDC_PUSH_ANIMATE                1462
#define IDC_PAK_TREE                    1466
#define IDC_CHECK_REPLACE               1467
#define IDC_RADIO_EXP_SELECTED          1468
#define IDC_EDIT_SOURCE                 1469
#define IDC_DT2_COLOR_TOLERANCE         1471
#define IDC_DT2_COLOR_TOLERANCE_SPIN    1473
#define IDC_DT2_CT_STATIC               1475
#define IDC_DT1_BUTTON_MOUSE_GUI        1477
#define IDC_BUTTON_COLOR                1478
#define IDC_BUTTON_AUTO16               1479
#define IDC_BUTTON_CHECK_ALL            1480
#define IDC_BUTTON_SELECT_ALL           1481
#define IDC_BUTTON_AUTO                 1482
#define IDC_EDIT_DESTINATION_DIR        1483
#define IDC_BUTTON_UNCHECK_ALL          1484
#define IDC_RADIO_OUTPUT_ALT            1485
#define IDC_RADIO_DONT_REMOVE_CACHE     1486
#define IDC_RADIO_EXP_SPECIFIC          1487
#define IDC_TST_TAB                     1488
#define IDC_TST1_COMBO_WAD              1489
#define IDC_TST1_LIST_IMAGES            1490
#define IDC_TST1_BUTTON_PREVIEW         1491
#define IDC_TST1_BUTTON_MOUSE_GUI       1492
#define IDC_TST1_STATUS                 1493
#define IDC_TST2_COLOR_TOLERANCE_STATIC 1494
#define IDC_TST2_COLOR_TOLERANCE        1495
#define IDC_TST2_COLOR_TOLERANCE_SPIN   1496
#define IDC_TST2_COMBO_SIZE             1497
#define IDC_TST2_COMBO_SHAPE            1498
#define IDC_TST2_COMBO_AMOUNT           1499
#define IDC_TST2_STATIC1                1500
#define IDC_TST2_STATIC2                1501
#define IDC_TST2_STATIC3                1502
#define IDC_TST2_STATIC4                1505
#define IDC_EDIT_DEFAULT_PALETTE        1506
#define IDC_BUTTON_DEFAULT_PALETTE      1507
#define IDC_BUTTON_EDIT_PALETTE         1509
#define IDC_CHECK_BUILD_OPTIMIZED       1510
#define IDC_EDIT_HL_DIRECTORY           1511
#define IDC_BUTTON_HL_DIR               1512
#define IDC_RADIO_CLIPBOARD             1513
#define IDC_EDIT_FILE                   1514
#define IDC_BUTTON_FILE                 1515
#define IDC_RADIO_LET_ME                1516
#define IDC_LIST_WADS                   1520
#define IDC_EDIT_EXISTING_WAD           1521
#define IDC_BUTTON_EXISTING_WAD         1522
#define IDC_BUTTON_PROPERTIES           1525
#define IDC_RADIO_IGNORE                1526
#define IDC_RADIO_OVERWRITE             1527
#define IDC_RADIO_RENAME                1528
#define IDC_RADIO_EXISTING_WAD          1529
#define IDC_EDIT_WAD_FILE               1530
#define IDC_EDIT_WILDCARD               1531
#define IDC_BUTTON_WAD                  1532
#define IDC_RADIO_OPEN_WAD              1533
#define IDC_COMBO_OPEN_WAD              1534
#define IDC_STATUS                      1535
#define IDC_STATUS2                     1536
#define IDC_RADIO_ANY_SIZE              1539
#define IDC_STATIC_PIXELS_W             1541
#define IDC_STATIC_PIXELS_H             1542
#define IDC_STATIC_SCALE_X              1543
#define IDC_STATIC_SCALE_Y              1544
#define IDC_STATIC_PERCENT_X            1545
#define IDC_STATIC_PERCENT_Y            1546
#define IDC_RADIO_CROP                  1547
#define IDC_RADIO_RESIZE                1548
#define IDC_RADIO_ERROR                 1549
#define IDC_RADIO_MAINTAIN_ASPECT       1550
#define IDC_RADIO_STRETCH_TO_FIT        1551
#define IDC_CHECK_PURE_BLUE_PIXELS      1553
#define IDC_RADIO3                      1554
#define IDC_RADIO_BLEND_OVERALL_COLOR   1554
#define IDC_RADIO4                      1555
#define IDC_RADIO_BLEND_SPECIFIC_COLOR  1555
#define IDC_TREE_IMAGES                 1555
#define IDC_SLIDER_THUMBNAIL_SIZE       1557
#define IDC_STATIC_THUMB_SIZE           1558
#define ID_ZOOMVALUE_STATUSBAR          2000
#define ID_CONSTRAIN_STATUSBAR          2010
#define ID_ZOOM                         2771
#define ID_FILE_BROWSE                  2774
#define ID_VIEW_OPTIONS                 2775
#define IDS_OUT_OF_MEM                  2776
#define ID_FILE_LOAD_PALETTE            2780
#define ID_TP_DROPPER                   2786
#define ID_TP_SELECTION                 2795
#define ID_TP_PAINT                     2796
#define ID_TP_ZOOM                      2797
#define ID_TP_TILE                      2798
#define ID_TP_FLAGS                     2799
#define ID_PALETTE_COLORS               2801
#define ID_TP_ANIMATE                   2809
#define ID_FILE_IMPORT_ASNEWWAL         2814
#define ID_FILE_IMPORT_INTO             2818
#define ID_POPUP_COPY_AS_BITMAP         2820
#define ID_EDIT_PASTE_AS_NEW_IMAGE      2823
#define ID_TOOLBAR_MIP1                 2824
#define ID_TOOLBAR_MIP2                 2825
#define ID_TOOLBAR_MIP4                 2828
#define ID_TOOLBAR_MIP3                 2829
#define ID_TP_REMIP                     2833
#define ID_VIEW_REMIP_OPTIONS           2836
#define ID_FILE_SELECT_FOLDER           2837
#define ID_FILE_CONVERT                 2838
#define ID_TP_BRUSH                     2839
#define ID_TP_PENCIL                    2840
#define ID_TP_BIGBRUSH                  2841
#define ID_TP_ERASER                    2842
#define ID_TP_LIGHTEN                   2843
#define ID_TP_DARKEN                    2844
#define ID_TP_SCRATCH                   2845
#define ID_VIEW_TOOL_OPTIONS            2848
#define ID_TP_BULLET_HOLES              2854
#define ID_TP_WIDTH                     2856
#define ID_TP_AMOUNT                    2857
#define ID_TP_SHAPE                     2858
#define ID_TOOL_WIDTH                   2859
#define ID_WIDTH_2_PIXELS               2861
#define ID_WIDTH_1_PIXEL                2862
#define ID_WIDTH_3_PIXELS               2863
#define ID_WIDTH_5_PIXELS               2865
#define ID_WIDTH_7_PIXELS               2866
#define ID_WIDTH_11_PIXELS              2867
#define ID_WIDTH_15_PIXELS              2868
#define ID_WIDTH_31_PIXELS              2869
#define ID_APPLY_LEAST                  2870
#define ID_APPLY_A_LITTLE_BIT           2871
#define ID_APPLY_MEDIUM                 2872
#define ID_APPLY_MORE                   2873
#define ID_APPLY_MOST                   2874
#define ID_TP_TINT                      2875
#define ID_SHAPE_SQUARE                 2876
#define ID_TOOL_SHAPE                   2877
#define ID_SHAPE_CIRCULAR               2878
#define ID_SHAPE_DIAMOND                2879
#define ID_TOOL_AMOUNT                  2880
#define ID_BRPOPUP_PROPERTIES           2882
#define ID_BRPOPUP_OPEN                 2883
#define ID_TESTPPAGE                    2884
#define ID_FILE_EXPORT                  2886
#define ID_TP_REPLACE                   2887
#define ID_BUTTON32889                  2889
#define ID_TP_SPRAY                     2889
#define ID_FILTER_BLEND                 2890
#define ID_FILTER_BLEND_HEAVY           2891
#define ID_FILTER_BLEND_LIGHT           2892
#define ID_BRPOPUP_COPY                 2893
#define ID_EDIT_COPYTILED               2894
#define ID_TP_FLOOD_FILL                2895
#define ID_TP_PATTERNED_PAINT           2898
#define ID_IMAGE_MIRROR                 2899
#define ID_BRPOPUP_COPYTILED            2900
#define ID_IMAGE_FLIP                   2901
#define ID_IMAGE_ROTATE                 2902
#define ID_TP_RECOLOR                   2903
#define ID_TP_SPRAY_RECOLOR             2905
#define ID_DRAWINGMODE_FREEHAND         2906
#define ID_DRAWINGMODE_LINE             2907
#define ID_DRAWINGMODE_POLYLINE         2908
#define ID_DRAWINGMODE_RAY              2909
#define ID_DRAWINGMODE_HOLLOW_RECT      2919
#define ID_DRAWINGMODE_SOLID_RECT       2920
#define ID_DRAWINGMODE_EDGED_RECT       2924
#define ID_IMAGE_BRIGHTNESS_CONTRAST    2925
#define ID_IMAGE_ADD_NOISE              2926
#define ID_IMAGE_BLEND                  2927
#define ID_IMAGE_EMBOSS                 2928
#define ID_IMAGE_EDGE_DETECT            2929
#define ID_IMAGE_GENERATE_MARBLE_TEXTURE 2931
#define ID_IMAGE_CONVERT_TEXTURES_QUAKE_TO_FROM_UNREAL 2932
#define ID_IMAGE_GENERATE_MARBLE_TILE_TEXTURE 2933
#define ID_EDIT_FREEUNDOMEMORY          2934
#define ID_IMAGE_DIFFUSE                2935
#define ID_IMAGE_FLIP_HORZ              2936
#define ID_IMAGE_FLIP_VERT              2937
#define ID_FILE_BATCH_CONVERSION        2938
#define ID_TP_RIVETS                    2939
#define ID_EDIT_PASTE_PACKAGE           2941
#define ID_PACKAGE_OPEN                 2942
#define ID_MENUITEM2943                 2943
#define ID_EDIT_RENAME                  2944
#define ID_POPUP_DELETE                 2945
#define ID_PACKAGE_ADD                  2946
#define ID_EDIT_PASTE_OVER              2947
#define ID_EDIT_DELETE                  2948
#define ID_PACKAGE_EXPORT               2950
#define ID_IMAGE_OFFSET                 2951
#define ID_IMAGE_SHARPEN                2952
#define ID_COLORS_SWAP_INDEXES          2954
#define ID_COLORS_EDIT_PALETTE          2955
#define ID_COLORS_LOAD_PALETTE          2956
#define ID_COLORS_SAVE_PALETTE          2957
#define ID_COLORS_COUNT_COLORS_USED     2958
#define ID_COLORS_TRANSLATE             2959
#define ID_IMAGE_RESIZE                 2960
#define ID_SELECTION_SELECTALL          2961
#define ID_SELECTION_SELECTNONE         2962
#define ID_SELECTION_SELECT_NONE        2963
#define ID_SELECTION_SELECT_ALL         2964
#define ID_IMAGE_REDUCECOLORS           2965
#define ID_IMAGE_REDUCE_COLORS          2966
#define ID_REPEAT_FILTER_PICK0          2967
#define ID_REPEAT_FILTER_PICK1          2968
#define ID_REPEAT_FILTER_PICK2          2969
#define ID_REPEAT_FILTER_PICK3          2970
#define ID_SHOW_FINE_GRID               2971
#define ID_SHOW_COURSE_GRID             2972
#define ID_TOOLBAR_FINEGRID             2973
#define ID_BUTTON2974                   2974
#define ID_FILE_LOAD_Q2PALETTE          2975
#define ID_FILE_LOAD_Q1PALETTE          2976
#define ID_VIEW_DECAL                   2977
#define ID_EDIT_PASTE_SPECIALEFFECTS    2978
#define ID_PACKAGE_DRAG_COPY            2979
#define ID_PACKAGE_DRAG_MOVE            2980
#define ID_PACKAGE_DRAG_CANCEL          2981
#define ID_USE_AS_RIVET_SOURCE          2982
#define ID_USE_AS_LEFT_BULLET_SOURCE    2983
#define ID_USE_AS_RIGHT_BULLET_SOURCE   2984
#define ID_USE_AS_LEFT_PATTERN_SOURCE   2985
#define ID_USE_AS_RIGHT_PATTERN_SOURCE  2986
#define ID_TP_DECAL                     2988
#define ID_USE_AS_LEFT_DECAL_SOURCE     2989
#define ID_USE_AS_RIGHT_DECAL_SOURCE    2990
#define ID_ACCEL2991                    2991
#define ID_PACKAGE_REMIP_SELECTED       2992
#define ID_PACKAGE_REMIP_ALL            2993
#define ID_BUILD_POPUP_COPY             2994
#define ID_BUILDVIEW_POPUP_COPYTILED    2995
#define ID_BUILDVIEW_POPUP_COPY         2996
#define ID_BUILDVIEW_PROPERTIES         2997
#define ID_BUILDVIEW_POPUP_PROPERTIES   2998
#define ID_BUILDVIEW_POPUP_PASTE        2999
#define ID_BUILDVIEW_POPUP_DELETE       3000
#define ID_FILE_WLY                     3001
#define ID_PACKAGE_NEW_IMAGE            3002
#define ID_ACCEL3003                    3003
#define ID_TP_BLEND                     3004
#define ID_FILE_BROWSE2                 3005
#define ID_POPUP_COPYRESIZE             3006
#define ID_VIEW_SHOWSUBMIPS             3007
#define ID_FILE_REFRESH                 3008
#define ID_VIEW_RULES                   3009
#define ID_FILE_TEST_TXL                3010
#define ID_BVPOPUP_INFO                 3011
#define ID_BVPOPUP_DELETE               3012
#define ID_BVPOPUP_COPY_CLIPBOARD       3013
#define ID_BVPOPUP_COPY                 3014
#define ID_BVPOPUP_PASTE                3015
#define ID_IMAGE_ENLARGE                3016
#define ID_ACCEL3017                    3017
#define ID_FILE_TEST                    3018
#define ID_ACCEL3020                    3020
#define ID_FILE_BUGFIX                  3021
#define ID_TP_CLONE                     3022
#define ID_TP_RUBBER_STAMP              3023
#define ID_FILE_PAK                     3024
#define ID_PAKPOPUP_DELETE              3026
#define ID_PAKPOPUP_COPY                3027
#define ID_PAKPOPUP_PASTE               3028
#define ID_PAK_POPUP_OPEN               3029
#define ID_PAK_POPUP_DELETE             3030
#define ID_PAK_POPUP_CUT                3031
#define ID_PAK_POPUP_COPY               3032
#define ID_PAK_POPUP_RENAME             3034
#define ID_PAK_POPUP_PASTE              3035
#define ID_PAK_POPUP_NEW_FOLDER         3036
#define ID_PAK_POPUP_NEW_TXTFILE        3037
#define ID_PAK_POPUP_NEW_IMAGE          3038
#define ID_PAK_PLAYSOUND                3039
#define ID_PAK_POPUP_EXPORT             3040
#define ID_PAK_POPUP_IMPORT             3041
#define ID_FILE_DEBUG                   3044
#define ID_PACKAGE_RESIZE               3045
#define ID_WIZARD_COLOR_DECAL           3046
#define ID_WIZARD_WADMERGE              3047
#define ID_IMAGE_TILED_TINT             3048
#define ID_IMAGE_FIX_UNEVEN_LIGHTING    3050
#define ID_WIZARD_TEST                  3052
#define IDS_DEFAULT_PALETTE_FILE        11216
#define IDS_DEFAULT_Q2PALETTE_FILE      11216
#define IDS_DEFAULT_PALETTE_WILDCARD    11218
#define IDS_PALETTE_OFN_TITLE           11219
#define IDS_IMPORT_IMAGE_TITLE          11221
#define IDS_IMPORT_IMAGE_WILDCARD       11222
#define ID_ZOOM_DIALOGBAR               11223
#define ID_XYPOS                        11224
#define ID_WIDTH_HEIGHT                 11225
#define ID_BLANK_PANE                   11227
#define ID_BROWSE_BLANK                 11228
#define IDS_FILEOPEN_WILDCARD           11229
#define IDS_FILEOPEN_TITLE              11230
#define IDS_FILEOPEN_EXTENSION          11231
#define IDS_FILEBROWSE_TITLE            11232
#define IDS_FILE_CONVERT_WILDCARD       11233
#define IDS_DEFAULT_Q1PALETTE_FILE      11234
#define IDS_FILESAVE_TITLE              11235
#define IDS_FILEEXPORT_TITLE            11236
#define IDS_FILE_EXPORT_WILDCARD        11237
#define ID_IMAGE_EDIT_TOOLBAR           32794
#define ID_MODES_TOOLBAR                32795
#define ID_PALETTE_TOOLBAR              32800
#define ID_TOOLSETTINGS_TOOLBAR         32802
#define IDS_WAD3_PACKAGE                61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         3053
#define _APS_NEXT_CONTROL_VALUE         1559
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
